### ISSUE TITLE
Contracts from this repo are being compiled with different result when building locally

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#100]
Basically all smart contracts that are presented in this repo are producing builds that differs from those saved in the same repo. This makes contributing not very comfortable.

<img width="546" alt="Screenshot 2023-11-29 at 8 04 39 PM" src="https://github.com/tact-lang/tact/assets/42098239/5f35459c-aa3a-4411-be84-666f745a83af">

Steps to reproduce:
1. Clone repo
2. run `yarn install`
3. run `yarn gen` or `yarn test`

**Comment by howardpen9** [comment]
I think because the code in `example` folder in this repo is outdated.

**Comment by anton-trunov** [comment]
We could probably just add autogenerated things to `.gitignore` and stop committing those to the repo. I would guess nobody checks diffs between old and new auto-generated files because those are not really readable

**Comment by anton-trunov** [comment]
Fixed in PR #199
