### ISSUE TITLE
Grammar allows l-value conditionals

### ISSUE THREAD

**Issue by verytactical** [tact-lang/tact#1036]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
a == a ? a : a = 1;
```

### Relevant Tact/build system log output

```shell
Assignments are allowed only into path expressions, i.e. identifiers, or sequences of direct contract/struct/message accesses, like "self.foo" or "self.structure.field"
```

### What happened?

Compiler shows the error message

### What did you expect?

Should it even be a valid (according to grammar) expression?

Also grammar is confusing and disagrees with other programming languages. Usually it goes like this:

```
foo = bar "?" foo ":" foo
    | bar "=" foo
```

so that `true ? a : b = 1` is parsed as `true ? a : (b = 1)`

If we intend to do overparsing (i.e. lenient grammar and error messages on further semantic pass, primarily for error readability), we're not entirely consistent with it here.

I would suggest not allowing nested ternary operators and assignments at all, but that might lead to breakage of existing code, and we should also be consistent there (for example, `a / b / c` and `a ** b ** c` are confusing to most users too).

**Comment by novusnota** [comment]
AFAIK, grammar allowed any expressions there in order for further analysis to be able to provide better error messages and exclude all non-path expressions

**Comment by anton-trunov** [comment]
There was indeed a decision to make the grammar less precise and handle some cases, including this one at a later state: during type checking as for this case, or during AST nodes creation as for the case of function/constant attributes.

The intention was to improve error reporting.
