### ISSUE TITLE
exists expects a direct type as first argument

### ISSUE THREAD

**Issue by Jobians** [tact-lang/tact#1063]
Error: contracts/simple_counter.tact:73:11: exists expects a direct type as first argument      Line 73, col 11:                                  72 |                                          > 73 |       if (self.participants.exists(me)) {                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by anton-trunov** [comment]
@Jobians please post a reproducible example
