### ISSUE TITLE
Backport Node.js compatibility layer for version < 22 for v1.5.x

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#1078]
Backport #1008 to a different branch, starting from the tag `v1.5.2`

**Comment by novusnota** [comment]
Done in https://github.com/tact-lang/tact/tree/backports-for-1.5.3

**Comment by anton-trunov** [comment]
https://github.com/tact-lang/tact/releases/tag/v1.5.3

Published on NPM: https://www.npmjs.com/package/@tact-lang/compiler/v/1.5.3
