### ISSUE TITLE
Add `storeStringTail` method to stdlib

### ISSUE THREAD

**Issue by Shvandre** [tact-lang/tact#1115]
As suggested in chat.

**Comment by Shvandre** [comment]
Main purpose of this function is to store onchain metadata of tokens. (And, maybe, add comments to transfers onchain).

Speaking about onchain matadata, it should not be done like that, and the standard concerning onchain metadata should be rewritten - it is poorly supported now and indexers do not want to support it in the future (at least Subbotin from tonapi wrote so). Recently there was more discussion in tondev about it. 

Above I mean discussion in TON Dev Chat starting on this message. https://t.me/tondev/270560

**Comment by Shvandre** [comment]
This functionality is already implemented in StringBuilder and can be found here: https://docs.tact-lang.org/ref/core-strings/

**Comment by anton-trunov** [comment]
@Shvandre did you mean https://docs.tact-lang.org/ref/core-strings/#begintailstring? Can you provide a self-contained example here for future reference?

**Comment by Shvandre** [comment]
> @Shvandre did you mean https://docs.tact-lang.org/ref/core-strings/#begintailstring? Can you provide a self-contained example here for future reference?

Yes. I meant exactly that link. Here is an example of building onchain metadata:

```
fun toTextCell(text: String): Cell {
    let sb: StringBuilder = beginTailString();
    sb.append(text);
    return sb.toCell();
}

fun buildCollectionContentCell(): Cell {
    let collectionContentDict: map<Int as uint256, Cell> = emptyMap();
    collectionContentDict.set(sha256("name"), toTextCell("aba"));
    collectionContentDict.set(sha256("description"), toTextCell("caba"));
    collectionContentDict.set(sha256("image"), toTextCell("lol"));

    return beginCell()
    .storeUint(0, 8)
    .storeBit(true)
    .storeRef(collectionContentDict.asCell()!!)
    .endCell();
}
```
