### ISSUE TITLE
Syntax question: What does contract attribute @interface("...") do?

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#112]
What does `@interface("...")` placed right before a contract or trait definition do?

It's described as a contract attribute in the [grammar.ohm#65](https://github.com/tact-lang/tact/blob/3ca10a868d786c1eff7ed56f4e479637e93c041c/src/grammar/grammar.ohm#L65) and there are few example usages of such syntax across the present Tact repository (mainly in stdlib), but no description or even mention of such thing on [tact-by-example](https://tact-by-example.org) or [official docs](https://docs.tact-lang.org).

**Comment by alepop** [comment]
@novusnota after contract compilation you can see a get method in compiled contract which allow you to get supported interfaces by the contract. https://github.com/tact-lang/tact-template/blob/6a14347f2973844799cc1f2e67ea38843d612b70/sources/output/sample_SampleTactContract.code.fc#L69C3-L69C23

**Comment by novusnota** [comment]
To be clarified in https://github.com/tact-lang/tact-docs/issues/286
