### ISSUE TITLE
AstNumber is weird

### ISSUE THREAD

**Issue by verytactical** [tact-lang/tact#1129]
Apparently we [store](https://github.com/tact-lang/tact/blob/main/src/grammar/grammar.ts#L1109-L1111) `0x1000` as `1000n` (decimal) along with the base, and I'm unsure how that works with `0xFFFF`.

For the rest of the code it doesn't make any sense to know what base was used to enter the literal: in any base number would be the same.

By the fact `base` is used in sources 5 times and `value` is used 14, we can conclude we have 9 bugs, even though reproducing them might be not that obvious.

**Comment by anton-trunov** [comment]
![telegram-cloud-photo-size-2-5406818751820720633-x](https://github.com/user-attachments/assets/40ca48fc-b020-4d98-b243-afed323238c7)
