### ISSUE TITLE
Describe how to use TVM assembly from Tact

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#1142]
As of now, one needs to create a FunC function, and then import the file with it and wrap the function into a `native` one in Tact

Related to tact-lang/tact#1154 and tact-lang/tact#1145 

UPD: Tact 1.5 support `asm`-functions natively, no need to go via FunC

**Comment by anton-trunov** [comment]
Basically tact-lang/tact#1057 is the same issue
