### ISSUE TITLE
Docs: check in CI examples with full contracts actually compile

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#1152]

**Comment by novusnota** [comment]
Yup, awesome idea. Should be applied mostly to Cookbook, once it gets updated structure tact-lang/tact-docs#142.

UPD: Got an idea: to gather all code blocks and look for `import` statements and `contract` declarations — if they're both present, then try to 1. `check()` and 2. `build()` the file. That's it for the tests!

**Comment by novusnota** [comment]
This is actually done for the Cookbook already. Moreover, the script that runs such checks in CI is perfectly runnable locally, see: `docs/scripts/check-cookbook-examples.js`
