### ISSUE TITLE
Tact produces FunC code with errors

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#118]
Some errors, such as some type errors, are not caught by the Tact-FunC transpiler, but the FunC compiler would report errors on the FunC code generated by Tact.

This is not acceptable, and Tact should always produce error-free FunC code.

**Comment by 0kenx** [comment]
For example
```
"abc".asSlice().loadUint(8);
```
gives error: Func compilation error: error: lvalue expected before `~__tact_load_uint`

where as
```
let s: Slice = "abc".asSlice();
s.loadUint(8)
```
compiles without errors.

**Comment by tonMaxi** [comment]
1

**Comment by anton-trunov** [comment]
You are totally right, well-typed Tact code should not provoke any FunC typechecking errors. Will fix the concrete [example](https://github.com/tact-lang/tact/issues/118#issuecomment-1879258362) you provided in Tact v1.3.0 release most likely. Although it's hard to ensure this in general, property-based randomized testing (see issue #133) usually gets good results in terms of hardening compiler implementations against such bugs. It might take several months to build this infrastructure for us, though. In the mean time, I'd really appreciate reporting Tact-FunC bugs like this one.
