### ISSUE TITLE
Docs: rewrite or remove the "Programmatic API" page

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#1183]
It's rather obsolete.

![image](https://github.com/user-attachments/assets/2ed5cb15-8a50-453c-9b65-d99cc2ce98e8)

We can either update it or, considering that the APIs are frequently updated, remove it for the time being, since the best documentation in such cases of frequent updates is simply to look into the compiler sources.

**Comment by anton-trunov** [comment]
Yeah, there is zero API stability guarantees provided by Tact. We should just document changes in the changelog and that's it. Let's remove this page
