### ISSUE TITLE
Tests randomly fail when generated grammar is from another version of code

### ISSUE THREAD

**Issue by verytactical** [tact-lang/tact#1243]
- Checkout some branch, modify grammar, generate `grammar.ohm-bundle.*`
- Make sure tests pass
- Checkout original branch
- Now tests fail, because we forgot to run `yarn gen:grammar`

It's not nice stepping on rakes while doing development. We should just automatically run `gen:grammar` before `test`.

The only downside is that in CI we'll run `gen:grammar` twice. Given the generation is idempotent, this shouldn't be a problem.

Also I suspected there would be an issue if we pass parameters, `yarn test path/to/file.spec.ts`, but it turns out `yarn` doesn't do anything quirky, and it's simple concatenation. As long as `jest` is the last executable in script, passing parameters should work correctly.

**Comment by novusnota** [comment]
> The only downside is that in CI we'll run gen:grammar twice. Given the generation is idempotent, this shouldn't be a problem.

Nope! CI runs `yarn coverage`, while in #1244 you've added the `gen:grammar` into the `test` script, so we're good :)
