### ISSUE TITLE
Add Blueprint to CI

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#129]
We need to test the development version of Tact is compatible with [Blueprint](https://github.com/ton-org/blueprint).

For reference, [this](https://github.com/tact-lang/tact/blob/fe06bfbc4c8728db3d9ae95df29be3e7a8be0aea/.github/workflows/tact.yml#L51-L59) is how tact-template integration is checked in CI.

Related issue: https://github.com/tact-lang/tact/issues/67

**Comment by Gusarich** [comment]
This will create a potential for fails in case if something breaks in Blueprint itself

**Comment by anton-trunov** [comment]
Yeah, that's the point -- to catch incompatibilities between Tact and Blueprint early

**Comment by anton-trunov** [comment]
In case it gets in the way of Tact development, I can override CI fails due to some Blueprint issues and merge anyways. But at least we will know about those before making new releases
