### ISSUE TITLE
Support address string literals

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#13]
```
let a1: Address = "EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N";
```

Useful for contracts with constant addresses

This is a little more readable than

```
newAddress(0, 0x83dfd552e63729b472fcbcc8c45ebcc6691702558b68ec7527e1ba403a0f31a8)
```

for users looking at verified sources and understanding which address they're looking at

**Comment by ex3ndr** [comment]
More like: `address("EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N")`.

Also: `cell("...")` and `slice("...")`

**Comment by talkol** [comment]
I wish we could have hex strings too, I hate base64 so much :D

**Comment by ex3ndr** [comment]
Added in `v1.0.0-rc9`
