### ISSUE TITLE
Do we need binary & and | operations

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#14]
```
i1: Int = 1234 & 0xff; 
```

This is low level stuff so not sure it's a good idea

Need to research Solidity contracts and see if there are good use-cases for this that can't be handled with simple Bools

**Comment by ex3ndr** [comment]
I believe that this is quite low level stuff, it is also not really clear how it works in the world of 257 signed ints. Meanwhile if someone want to do some advanced stuff always can downgrade to a func and perform any magic they want including bitwise operations.

**Comment by Gusarich** [comment]
This is already implemented in https://github.com/tact-lang/tact/commit/15a358761489bbacd70f7169736504b7abc6eecd
