### ISSUE TITLE
Handling masterchain (multiple workchains)

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#15]
Some func contracts parse the workchain of addresses - eg. [nominator-pool](https://github.com/ton-blockchain/nominator-pool/blob/2f35c36b5ad662f10fd7b01ef780c3f1949c399d/func/pool.fc#L329)

This is currently not easily supported by tact stdlib

This brought a discussion whether users should be encouraged to deploy/develop contract on the masterchain since this is advanced stuff where users can easily find themselves having bugs due to the higher cost of gas (consider a jetton that needs to send a notification across chains and there's not enough gas for this message to cross)

The idea that came up is to disallow masterchain in the compiler unless an explicit flag is used so users are informed of the risk

**Comment by ex3ndr** [comment]
Implemented in `v1.0.0-rc9`. Maps are not checked though and it seems it would be impossible to check without accessing each item anyway.
