### ISSUE TITLE
Tact lacks libraries for major network contracts.

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#150]
While `@stdlib/deploy`, `@stdlib/ownable`, and `@stdlib/stoppable` are available, which is great, people also frequently need to interact with standard smart contracts such as Jettons or NFTs. Therefore, there should be definitions for messages of such contracts in `@stdlib/` as well.

**Comment by vitorpy** [comment]
I'd like to add support for Jettons and NFTs to the stdlib. Is it OK to work on this?

**Comment by anton-trunov** [comment]
@vitorpy Sure! We just to make sure we have a clear plan for this. Perhaps @Gusarich can share some of his thoughts. Also, there is existing work on this by @howardpen9: https://github.com/howardpen9/jetton-implementation-in-tact

**Comment by Gusarich** [comment]
The problem with implementing these standards in Tact is that it doesn't have full compatibility with TL-B in terms of defining messages.
For example, we can't define `Either` for a Tact message, and it's used in tokens for `forward_payload`. The implementation from Howard defines it as `forward_payload: Slice as remaining;`, but it means that developer will have to compose the `forward_payload` with `Either` bit himself in TS.

**Comment by vitorpy** [comment]
@Gusarich Maybe we could formulate on which ways Tact isn't fully compatible with TL-B and I could work on those? I do need help spec-ing it, though.

**Comment by Gusarich** [comment]
@anton-trunov let's close this one as it's similar to a newer #322

**Comment by anton-trunov** [comment]
Sure
