### ISSUE TITLE
Some stdlib libraries are not documented

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#151]
https://github.com/tact-lang/tact/tree/main/stdlib/libs

`config`, `content` and `dns` libraries are present in repository and listed in changelog, but not documented.

**Comment by novusnota** [comment]
@Gusarich good suggestion. I've added those in https://github.com/tact-lang/tact-docs/issues/51.

You can see them live on: https://docs.tact-lang.org/language/libs/overview.
If everything's good there, then we can close this issue :)

**Comment by Gusarich** [comment]
LGTM
