### ISSUE TITLE
`@stdlib/content` library is not complete

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#153]
Currently it only provides a single method `createOffchainContent`. But the standard also described two ways (snaked and chunked) of storing on-chain content.
We also need a simple way to build on-chain content for tokens, at least with one of these two ways.

https://github.com/ton-blockchain/TEPs/blob/master/text/0064-token-data-standard.md

**Comment by Gusarich** [comment]
Actually after looking again at this issue I see that there's no point of trying to define some helper functions for this and I'm not even sure if it's possible to define some that will be helpful.

Onchain data is just a dictionary where values are stored either in snake or chunked format. For small values (like numbers or short links) it's easy to compose all that and we could define a simple helper function which would reduce the amount of code, but if developer needs to store something larger (long text descriptions, images, etc), they'll probably need to implement that themselves anyway.

**Comment by anton-trunov** [comment]
Let's then close it for now and revisit if there is a request from Tact users
