### ISSUE TITLE
Allow dumping of Address types

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#16]
```
dump() not supported for type: Address
```

**Comment by talkol** [comment]
I think it's fine to dump in this format (which should be easier):

```
0:83dfd552e63729b472fcbcc8c45ebcc6691702558b68ec7527e1ba403a0f31a8
```

**Comment by ex3ndr** [comment]
Well, it is not trivial. We have to write out hex encoder.

**Comment by logvik** [comment]
To compare in the current version:
in tact
```
dump(beginCell().storeAddress(ctx.sender).endCell().hash());
```
in tests on ts
```
console.log(
            "address hash: " +
                BigInt(
                    "0x" + beginCell().storeAddress(contract.address).endCell().hash().toString("hex")
                )
        );
```

**Comment by ex3ndr** [comment]
I doubt that this would be an address

**Comment by logvik** [comment]
It is just a way how to dump address in tact and compare via ts. Just for a case, if somebody will face with this issue, to find how to solve this issue right now.

**Comment by EmelyanenkoK** [comment]
We had address encoder task in funC contest №2, there are a few opensourced solutions, for instance:
https://github.com/ton-blockchain/func-contest2-solutions/blob/main/5.fc

**Comment by howardpen9** [comment]
<3

**Comment by howardpen9** [comment]
Is this solve as well or should be implement in Tact? 

cc @anton-trunov , 

Reference:

https://tact-by-example.org/02-addresses

**Comment by BorisWild** [comment]
I'm using blueprint with @tact-lang/compiler version "1.4.2" and still can't dump Address `dump(myAddress())` returns nothing...

**Comment by anton-trunov** [comment]
@BorisWild What have you tried? Are you sure you provided enough gas? Because dumping is computationally expensive

**Comment by BorisWild** [comment]
Thank you) you are right! Not enough ton on balance...
