### ISSUE TITLE
Update stdlib/stdlib.fc distributed with Tact

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#164]
At least some comments need fixes: https://github.com/tact-lang/tact-docs/pull/70#discussion_r1508269863

**Comment by Gusarich** [comment]
do you mean the stdlib.fc file itself?
if so, what's the point of updating comments in it? do people have to look there sometimes for some reason?

**Comment by anton-trunov** [comment]
Just for the sake of consistency
