### ISSUE TITLE
Generic `for` loop

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#168]
`for` loops are essential for almost any programming langauge and we should have them in Tact too.
Syntax can be identical to most programming languages like C++ or Typescript:
```tact
for (statement; expression; statement) {
    // body
}
```

so, for example:
```tact
let m: Map<Int, Int> = emptyMap();
for (let i: Int = 0; i < 10; i += 1) {
    m.set(i, i * i);
}
```

**Comment by Bahmn1118** [comment]
Ye

**Comment by anton-trunov** [comment]
Closing this for now, as it needs a compelling use case
