### ISSUE TITLE
Allow blockless loop and condition bodies

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#170]
Currently, grammar for conditions and loops look this way: https://github.com/tact-lang/tact/blob/7ed5e05dc0fcbc880f76fe326ea03aae69a3d966/src/grammar/grammar.ohm#L116-L121

The `"{" Statement* "}"` part is being repeated in each of these. However, if we just replace it with `Statement`, it would include `StatementBlock` by itself (so previous syntax won't break) but also allow blockless bodies if needed, same as in many popular programming languages:
```tact
let x: Int = 1;
while (x < 10) x *= 2;
return x;
```

**Comment by anton-trunov** [comment]
The issues I see here are basically:

- smart contracts should encourage explicitness
- we will have the [Dangling else ambiguity](https://en.wikipedia.org/wiki/Dangling_else) which we will need to resolve
- also, as noted by @novusnota, sometimes people can have semantically incorrect indentation with this change, which together with auto-formatting of source code can lead to missed bugs
