### ISSUE TITLE
Issue with emit log and CARRY_REMAINING_GAS Mode compatibility in Tact

### ISSUE THREAD

**Issue by ionfi-jeff** [tact-lang/tact#176]
I'm currently developing a contract using func, and I've incorporated the emit log functionality, originally implemented in Tact, directly into my func code. Here's the code I'm referencing:
https://github.com/tact-lang/tact/blob/8cb0d463b5c06471b5ce08dd9b7749e49e6ee6cd/stdlib/std/send.tact#L71-L79

However, I've encountered an issue where the emit log and messages sent with CARRY_REMAINING_GAS mode (mode 64) seem to be incompatible. When a contract attempts to send a message with both a log and CARRY_REMAINING_GAS mode simultaneously, it results in either action code 37 or action code 40.

One of the main challenges in debugging this issue is its unpredictability—sometimes it occurs, and other times it doesn't, with no clear pattern. It depends on the code.

Could someone give me detailed explanation about the emit function and its compatibility with CARRY_REMAINING_GAS mode? Any guidance or insights would be greatly appreciated.

Thank you.

**Comment by Blackboy369** [comment]
Cool job

**Comment by Gusarich** [comment]
Why would you want to send log message with any value attached? It's not even supported in it.
That's why the mode 0 is hardcoded in Tact's standard library there.
