### ISSUE TITLE
Create a JSON schema for `tact.config.json`

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#178]
This can be used to get intelligent completion within Visual Studio Code or any editor supporting LSP (Neovim, Helix, etc.), which has access to `tsserver`.

User of the schema needs to add one more property to their `tact.config.json` to enable completion and hover — `"$schema": "link to the json file"`.

Here's an example of using `$schema`:
![image](https://github.com/tact-lang/tact/assets/68142933/982a4280-b3f5-4e7d-bcd4-16dcfa662f26)

I'd suggest putting the schema file right in the root of this repo, near to `tact.config.json`. Alternatively, it can be put to `grammar/`, if that folder is still maintained :)

Links:
* JSON Schema description: https://json-schema.org/
* Reference implementation: https://github.com/martinring/tmlanguage/blob/master/tmlanguage.json
* `tact.config.json` field definitions in [parseConfig.ts](https://github.com/tact-lang/tact/blob/main/src/config/parseConfig.ts)

**Comment by anton-trunov** [comment]
Love the idea!

We should also add schema adherence checks for all `tact.config.json` files in the repo to our CI
