### ISSUE TITLE
Contributing guide is missing

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#186]
In addition to #130, we should have a contributing guide explaining the workflow for working on Tact contributions from the community.

For instance, we should mention in the guide that PRs should have opened and discussed issues before working on them. And also, a PR should be focused on one issue it is trying to resolve. Carpet PRs targeting multiple non-related issues are discouraged. Btw, we as a team should adhere to this policy too, to set an example.

**Comment by byakuren-hijiri** [comment]
Another idea would be to add the [`.github/pull_request_template.md`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) file.

We could specify a short checklist for contributors, for example:
```
Closes #<issue number>

* [ ] I have updated CHANGELOG.md
* [ ] I have added unit tests to check possible regressions
```

**Comment by spartan124** [comment]
This would be nice to have. Also contributors can attach video or loom link to PRs to showcase changes made so reviewers can easily check and merge

**Comment by novusnota** [comment]
This page from Gleam project may suit as a good starting point for describing the compiler structure (`ARCHITECTURE.md`, perhaps?): https://github.com/gleam-lang/gleam/tree/main/docs/compiler

UPD: Nice post on the topic, https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

**Comment by anton-trunov** [comment]
Looks great, indeed! Thanks @novusnota

**Comment by novusnota** [comment]
https://github.com/nayafia/contributing-template — found an awesome template to start off of.

Additionally, we should introduce a couple of templates for new issues — bug report, feature suggestion/proposal, etc.

**Comment by Gusarich** [comment]
@anton-trunov this one is already completed and should be closed, right?
