### ISSUE TITLE
Support more boolean operations in constant evaluation

### ISSUE THREAD

**Issue by byakuren-hijiri** [tact-lang/tact#195]
[`reduceBool`](https://github.com/tact-lang/tact/blob/cd34466ceb552977518ce60af10efad6f06ce69b/src/types/resolveConstantValue.ts#L62) is responsible for evaluating Tact constants in compile-time. Currently it supports only `&&` and `||` for booleans, and there is the TODO comment to add more operations: https://github.com/tact-lang/tact/blob/cd34466ceb552977518ce60af10efad6f06ce69b/src/types/resolveConstantValue.ts#L77

The following boolean operations could be easily added: `==` and `!=`.

We could also consider adding the following operations between integer constants that results in boolean:  `!=`, `>`, `<`, `>=`, `<=`, `==`.

In general, this feature is quite useful, as it allows the creation of constants with meaningful names instead of "magic values" in code, which is considered a best practice in programming. However, the need for these specific cases is quite rare.

Found while working on #133.

**Comment by anton-trunov** [comment]
I think this has been resolved with the recent refactor of the constant evaluator
