### ISSUE TITLE
Switch addition to bitwise 'or' for `SendParameters`'s mode value

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#203]
As @Gusarich mentiones, the bitwise 'or' operation (`|`) is idempotent: https://github.com/tact-lang/tact/issues/180#issuecomment-2021925246

**Comment by Gusarich** [comment]
Do you mean simply changing the operation in examples and tests from this repo?

**Comment by anton-trunov** [comment]
Yep, here and in tact-docs
