### ISSUE TITLE
`newAddress()` should be const eval

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#214]
## Problem

```
contract A {
    myAddress: Address = newAddress(0, 0);
    receive("set") {
        self.myAddress = sender();
    }
}
```

gives error `Cannot reduce expression to a constant Address`. In order to avoid this any `Address` type variable must be initialized in the `init()` section.

## Proposal

`newAddress()` should be const eval. This would allow more consistent code, i.e all data types (int, bool, Address) can be initiated in the declaration section of the contract.

**Comment by Gusarich** [comment]
It can't always be calculated in compile-time, because you could provide variable parameters there.
But calculating constant addresses is a nice optimization.

**Comment by Gusarich** [comment]
Actually, there's compile-time function `address()` for creating constant addresses from strings already

**Comment by anton-trunov** [comment]
> Actually, there's compile-time function address() for creating constant addresses from strings already

@Gusarich But it's untested and undocumented!

**Comment by anton-trunov** [comment]
Let me re-open this issue for the time being, because `myAddress: Address = newAddress(0, 0)` indeed looks like something we could allow at first sight

**Comment by novusnota** [comment]
Do you mean that we should introduce another function, like `nullAddress()` or something, which will be equivalent to writing `newAddress(0, 0)` and would be a compile-time one?

**Comment by anton-trunov** [comment]
If we can compute `newAddress(a, b)`, where `a` and `b` are constants at runtime, then we don't need to introduce `nullAddress`

**Comment by Gusarich** [comment]
> Do you mean that we should introduce another function, like `nullAddress()` or something, which will be equivalent to writing `newAddress(0, 0)` and would be a compile-time one?

It'd be better to have `nullAddress()` (or maybe better `noneAddress()`) return `addr_none$00` which is [not the same](https://github.com/tact-lang/tact/issues/515#issuecomment-2205178642) as `newAddress(0, 0)`
