### ISSUE TITLE
Support StringBuilder.append chaining

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#23]
Make `StringBuilder.append` return itself, so we can write:

```
sb.append(self.s1).append(", your balance is: ").append(self.s5);
```

**Comment by anton-trunov** [comment]
Changing `append`'s signature would be go against (unimplemented yet) warnings like the one provoked by issue #6 in some existing code:

```tact
get fun hello(src: String): String {
    let builder: StringBuilder = beginString();
    builder.append("Hello, ");    // warning: unused return value of `append` method
    builder.append(src);          // warning: unused return value of `append` method
    return builder.toString();
}
```

To avoid this, we could introduce a new version of `append` with a new name (let's say `app` or `concat`) that returns the modified builder, or, for instance, introduce string interpolation into Tact, which would make the original example even more readable:

```tact
sb.append("${self.s1}, your balance is: ${self.s5}");
```

(this is a raw idea and a bit non-trivial to implement)
