### ISSUE TITLE
Add `xor` support

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#235]
`xor` should be added in stdlib.
```
@name(xor)
native xor(a: Int, b: Int): Int;
```
```
int xor(int x, int y) asm "XOR";
```

It's best to add it as an operator `^`.

**Comment by anton-trunov** [comment]
Duplicate of #119

**Comment by 0kenx** [comment]
BTW is there a bitwise NOT operator?

**Comment by anton-trunov** [comment]
no, there is no bitwise NOT operator at the moment, thanks for point that out
