### ISSUE TITLE
Compilation of a contract with a struct with more than 15 address fields fails with `TUPLE:integer does not fit into cell`

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#248]
Compilation of a contract with a bit too many struct fields:

```tact
struct Keys {
    key1: Address;
    key2: Address;
    key3: Address;
    key4: Address;
    key5: Address;
    key6: Address;
    key7: Address;
    key8: Address;
    key9: Address;
    key10: Address;
    key11: Address;
    key12: Address;
    key13: Address;
    key14: Address;
    key15: Address;
    key16: Address; // adding key16 makes compilation fail
}

contract Fail {
    foo: map<Int, Keys>;
    init() {}
    get fun foo(): Keys? {
        return self.foo.get(1);
    }
}
```

fails with the following error message:

```
Build script running, compiling Crowdfunding
⏳ Compiling...   > Fail: tact compiler
   > Fail: func compiler
[ 1][t 0][2024-04-13 08:45:06.018000][Fift.cpp:67]      top: <continuation 0x937418>
level 1: <continuation 0x9356c8> <continuation 0x933b38> <continuation 0x938950> <continuation 0x933b38> 4 <continuation 0x937418> **HERE** <continuation 0x95a340> 
level 2: <text interpreter continuation>

main.fif:114:   TUPLE:integer does not fit into cell
```

The same problem exists for messages as well.

**Comment by aleksandrGlebov** [comment]
Hi I have the same problem, were you able to solve it?

**Comment by Gusarich** [comment]
There are two limits related to this issue:
 * 16 return values from functions defined with asm
 * length 16 for tuples in `TUPLE` operation

We can easily overcome the second one by using `VARTUPLE` for longer ones, but to resolve the first one we will probably have to change the way tuples are used in Tact and I'm not yet sure if it's going to be easy or not.

What if we just forbid the usage of such variables in cases where it requires a `UNTUPLE` call and tell the developer that the limit for struct length here is 16? And in future we'll just remove that restriction when there's a fix for that.
