### ISSUE TITLE
`!!` does not allow using method calls on its return value

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#251]
For example, `self.map.asCell()!!.hash()` fails with the following error message

```
/main.tact:27:33: Syntax error: expected ";"  
Line 27, col 33: 
  26 |     get fun result(): Bool { 
> 27 |         return self.m.asCell()!!.hash() == 0; 
                                       ^ 
```

**Comment by novusnota** [comment]
The error doesn't just apply to `!!`, it's a more generic one.

For example, the following doesn't work:

![image](https://github.com/tact-lang/tact/assets/68142933/3aabb722-3390-4e3f-a041-6d76b85b7978)

Despite that `calculate_jetton_wallet_address()` returns the Slice:

![image](https://github.com/tact-lang/tact/assets/68142933/81784644-2fe8-4846-955d-0903f6550d2d)

And even wrapping stuff in additional parentheses doesn't work:

![image](https://github.com/tact-lang/tact/assets/68142933/482a353d-98ff-41a2-917d-b53143de76cf)

While the following works:

![image](https://github.com/tact-lang/tact/assets/68142933/bad747bd-c1d1-40d2-8e2a-a20880de4403)

_Images are taken from [Tact Telegram Chat](https://t.me/tactlang)_

**Comment by anton-trunov** [comment]
@novusnota This is not a more general error, this has to do with lvalues (`loadAddress` mutates its argument)
