### ISSUE TITLE
Struct fields punning, i.e. `{foo, bar}` should be syntactic sugar for `{ foo: foo, bar: bar }`

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#253]
This makes code more concise, so we should support it. This concerns messages too.

**Comment by vitorpy** [comment]
Planning to give this a try over the weekend, probably by extending the StructBody definition:

![image](https://github.com/tact-lang/tact/assets/12871/10cbfbf1-c1ab-4cc6-b909-d9782a58c3b2)

Let me know if the approach sounds sensible.

**Comment by anton-trunov** [comment]
@vitorpy Thanks for your interest! You need to look at `ExpressionNew`: https://github.com/tact-lang/tact/blob/d73a83691d469eeba832cf76c5c048dc0c5e805d/src/grammar/grammar.ohm#L177, since this is about defining *instances* of structs, not about declaring struct types.

**Comment by vitorpy** [comment]
> @vitorpy Thanks for your interest! You need to look at `ExpressionNew`:
> 
> https://github.com/tact-lang/tact/blob/d73a83691d469eeba832cf76c5c048dc0c5e805d/src/grammar/grammar.ohm#L177
> 
> , since this is about defining _instances_ of structs, not about declaring struct types.

Oh, that makes sense! Thanks!
