### ISSUE TITLE
Chaining methods after `!!` operator

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#258]
Chaining methods after `!!` operator is not supported.

```
extends fun foo(self: Cell): Bool {
    return true;
}

message M {
    c: Cell?;
}
contract A {
    receive(msg: M) {
        let result: Bool = msg.c??.foo(); //Syntax error: expected ";"
    }
}
```

`msg.c` has type `Cell?`, and `msg.c!!` has type `Cell`, thus it is expected that chaining it with `.foo()` should work.

**Comment by anton-trunov** [comment]
Duplicate of #251. Already fixed and will be available with the upcoming Tact 1.3.0 release
