### ISSUE TITLE
Constant structs are not supported

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#284]
The following snippet

```tact
struct A {
    x: Int;
    y: Int;
}

const a: Int = 5;
const b: Int = 6;

const D: A = A { x: a, b };
```

produces an error message like this

```
"<unknown>:13:14: Expected constant value, got A
Line 13, col 14:
  12 | 
> 13 | const D: A = A { x: a, b };
                    ^~~~~~~~~~~~~
```

while it is expected the error would point to the `b` in the struct definition (provided the field punning feature is available).

**Comment by vitorpy** [comment]
What would be the correct approach here to support const structs, something along the lines of a `reduceStruct` implementation that would reduce the struct to a const BoC?

**Comment by byakuren-hijiri** [comment]
I would also mention that fields cannot be initialized by struct instances. For example, the following snippet returns the same compiler error:

```
struct LVc {
    UxS4: String;
    KCNI_GZzVYYQ_: Bool;
}
contract __Vb {
    _vINF_u_NA_: LVc = LVc{UxS4: "", KCNI_GZzVYYQ_: false};
}
```

**Comment by anton-trunov** [comment]
@byakuren-hijiri That one looks cool! Let's create a separate issue for that and tag it "found-by-fuzzer"
