### ISSUE TITLE
Function identifiers are allowed to be shadowed in their bodies

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#307]
Both of the snippets below compile just fine, but should not, since variable shadowing is not allowed and functions in Tact are recursive by default:

```tact
fun rec(): Int {
    let rec: Int = 42;  // shadowing error
    return rec;
}
```

```tact
fun rec(): Int {
    let rec: Int = 42;  // shadowing error
    return rec();
}
```

**Comment by Gusarich** [comment]
@vitorpy since you've already opened a PR, can you leave a comment here so that I can assign you to this issue?

**Comment by vitorpy** [comment]
Sure thing - I'll see if I can find some time next week to get back to it.
