### ISSUE TITLE
Upgrade Node.js actions

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#320]
Here is what GitHub Actions reports:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by novusnota** [comment]
This change would also start automatically introducing `packageManager` field in the `package.json` due to https://github.com/nodejs/corepack feature
