### ISSUE TITLE
Extend standard library with new TVM instructions

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#324]
TVM Upgrades [2023.07](https://docs.ton.org/learn/tvm-instructions/tvm-upgrade-2023-07) and [2024.04](https://docs.ton.org/learn/tvm-instructions/fee-calculation-instructions) introduced many useful TVM instructions, including those for optimized work with fees.
We have to extend our standard library too.

**Comment by Gusarich** [comment]
depends on https://github.com/tact-lang/ton-opcode/issues/4 and https://github.com/tact-lang/ton-opcode/issues/5

**Comment by 0kenx** [comment]
We should have a stdlib that includes all [documented](https://docs.ton.org/learn/tvm-instructions/instructions) and [undocumented](https://github.com/ton-community/ton-docs/blob/main/docs/learn/tvm-instructions/instructions.csv#L954) opcodes.

**Comment by Gusarich** [comment]
Seems like https://github.com/tact-lang/tact-emulator doesn't support new opcodes yet: I'm getting `Invalid opcode` error in tests.
