### ISSUE TITLE
Note in JSON Schema that some fields are unused in Blueprint

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#329]
As Blueprint now [auto-sources `tact.config.json`](https://github.com/ton-org/blueprint/pull/96) and uses some of its properties as defaults, it's important to tell exactly which and draw the distinction in the use of `name` property — Blueprint uses it as the whole name of the project, while Tact compiler uses it merely as a prefix to the generated files.

**Comment by anton-trunov** [comment]
@novusnota Thanks so much for documenting it here. Let's also make sure to document these differences in tact-docs

**Comment by novusnota** [comment]
Yup, here's the relevent PR: https://github.com/tact-lang/tact-docs/pull/225
