### ISSUE TITLE
Incorrect error message for non-initialized contract constants

### ISSUE THREAD

**Issue by byakuren-hijiri** [tact-lang/tact#332]
```
contract SampleTactContract with Deployable {
    const u4: Int;
}
```

Error message:
```
Tact compilation failed
contract.tact:8:5: Abstract function doesn't have abstract modifier
Line 8, col 5:
  7 | contract SampleTactContract with Deployable {
> 8 |     const u4: Int;
          ^~~~~~~~~~~~~~
  9 |   }
```

Expected: Something [like this](https://github.com/tact-lang/tact/blob/79e87d5b2170a19aa44a34325c183f9ffe244155/src/types/resolveExpression.ts#L381), e.g. `Contract constant is not initialized`.

---

When adding such a constant in the `ASTContract` entry directly, compilation fails with an exception [here](https://github.com/tact-lang/tact/blob/79e87d5b2170a19aa44a34325c183f9ffe244155/src/generator/writers/writeExpression.ts#L117), because `s` is `undefined`.

**Comment by anton-trunov** [comment]
Constant declarations should be forbidden for contracts and only allowed for traits

**Comment by byakuren-hijiri** [comment]
The issue is still present in `ac5b87abcaa13183a3fea0a499100b2bff8efdcc` for non-initialized trait constants:

```
trait bYO___ZJ__g_g {
    const x_B_y_H_8: Int;
}
```

Compilation error:
```
Error: ../TON-Projects/tact-template/sources/contract.tact:4:5: Abstract function doesn't have abstract modifier
Line 4, col 5:
  3 | trait bYO___ZJ__g_g {
> 4 |     const x_B_y_H_8: Int;
          ^~~~~~~~~~~~~~~~~~~~~
  5 | }
```

It is just about an incorrect error message which has a trivial fix.
