### ISSUE TITLE
Different FunC code after compilation

### ISSUE THREAD

**Issue by jokly** [tact-lang/tact#336]
**Description**

[Example project](https://github.com/jokly/tact-bug)
Contract structure: NFTItem -> NFTCollection

**Problem**

After compilation files with FunC code of NFTItem are different:

* `tact_NFTItem.code.fc` from NFTItem folder
* `tact_NFTItem.code.fc` from NFTCollection folder

Diff:

```
_ get_abi_ipfs() method_id {

    return "ipfs://QmYMHufVnBdJM9je3XUNKK8WGUHKHRgDkVg6ygjiTMu3hP";

}
```

**Comment by anton-trunov** [comment]
The hash is calculated based on the ABI, by adding traits (as explained in the repo's readme) you change your contract's ABI, so the hash changes. This is expected behavior.

**Comment by jokly** [comment]
Hello! Thank you for your reply.

Based on your answer, if contract `NFTCollection` use contract `NFTItem` I need to use build folder of `NFTCollection` contract for both in wrappers:

- NFTCollection: `export * from '../build/NFTCollection/tact_NFTCollection';`
- NFTItem: `export * from '../build/NFTCollection/tact_NFTItem';`

Is it right? I think it's not clear behavior
Can you explain why does FunC code of **NFTItem** depends on **NFTCollection** code and its traits?
