### ISSUE TITLE
Application of mutation functions on function returns leaks to FunC and errors there

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#348]
The following snippet:

```tact
contract Test {
    get fun test() {
        emptySlice().loadRef();  // ← this is the cause
    }
}
```

Produces this FunC compilation error:

```shell
Func compilation error: /test/tact_Test.code.fc:23:25: error: lvalue expected before `~load_ref`
     $global_emptySlice()~loadRef();
```

The error is not related to empty Slice having no references, but rather is about not being able to modify the value from the function return on the fly. The latter is justified and perfectly fine, but we should probably catch similar cases in Tact before they leak to FunC and cause errors there.

**Comment by novusnota** [comment]
Similar case to what I've described above:
![image](https://github.com/tact-lang/tact/assets/68142933/78fcdb3d-bbfb-453c-aeb0-08979c2b3f98)

And my response:
![image](https://github.com/tact-lang/tact/assets/68142933/67d77f7f-f43a-47f3-b9b8-e1460ba06022)

_Both taken from [Tact's Telegram group](https://t.me/tactlang)_

**Comment by Gusarich** [comment]
I mentioned this in #211 already

**Comment by novusnota** [comment]
Yeah, this is indeed a duplicate of #211
