### ISSUE TITLE
Cannot assign `skipBits()` return value due to type mismatch between FunC and Tact

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#349]
The function [`skipBits()`](https://docs.tact-lang.org/ref/core-cells#sliceskipbits) in the core library is a wrapper of `~skip_bits()` one in FunC, see: https://github.com/tact-lang/tact/blob/e080f7f180da318363584530b6801b3e7bb4d11e/stdlib/std/cells.tact#L75-L76

Its original return type is `(slice, ())`,  while the return type in Tact is specified as Slice. As such (or for some other, yet unknown reason) any attempts to assign its return value to a variable of type Slice fail.

**Comment by howardpen9** [comment]
niceeeee
