### ISSUE TITLE
Identifiers should be quoted in error messages

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#361]
Otherwise error messages can be confusing to users, for instance:

> Field initialized is not set

The `initialized` identifier should be quoted:

> Field 'initialized' is not set

**Comment by Gusarich** [comment]
Should it only affect variable/field identifiers or traits, functions, types too?

**Comment by anton-trunov** [comment]
Right, any identifier should be quoted for consistency, including functions, types, etc.
