### ISSUE TITLE
Unexpected behaviour using `StateInit` outside of contract context

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#367]
```
contract B {
    owner: Address;
    init(addr: Address){
        self.owner = addr;
    }
}

fun get_init(addr: Address): StateInit {
    return initOf B(addr);
}

contract A {
    receive("aa") {
        let c: StateInit = get_init(myAddress()); // fails
        // let c: StateInit = initOf B(myAddress()); // succeeds
    }
}
```
Build succeeds but execution fails with exit code 135: Code of a contract was not found

Moreover, the following also compiles
```
fun get_init(): StateInit {
    return initOf B(myAddress());
}
```
but clearly the context of the calling contract is not preserved when calling `myAddress()` from an external function.

**Comment by Gusarich** [comment]
@0kenx I can't reproduce the problem here. Copied the code, sent `aa` message to the contract `A` and no errors occured. Can you share the test source code too please?

**Comment by anton-trunov** [comment]
@Gusarich Let's then add the example posted by @0kenx to the test suite to resolve this issue

**Comment by Gusarich** [comment]
> @Gusarich Let's then add the example posted by @0kenx to the test suite to resolve this issue

I've actually added that in #521

**Comment by anton-trunov** [comment]
@Gusarich Looks like I missed it was that code :) Thanks.

@0kenx Closing this, feel free to re-open if the issue is not resolved
