### ISSUE TITLE
Use `ASTId` for names in AST

### ISSUE THREAD

**Issue by byakuren-hijiri** [tact-lang/tact#377]
- [x] Constants,
- [x] fields,
- [x] functions,
- [x] The `traits` field of `ASTContract` and `ASTTrait`
- [x] and other AST elements

typically use `string` referring to the name of the element. It could be replaced by `ASTId`, so we'll get additional information about the definition point of the related AST element, which is useful for users of the compiler's API and internally to generate warnings referring to that element.

**Comment by byakuren-hijiri** [comment]
Additionally we should consider that refactoring the `traits` field of `ASTContract` and `ASTTrait`.

Currently, we use `ASTString[]` to represent traits inherited by [other traits](https://github.com/tact-lang/tact/blob/d86aeab03534d8ccd2407d2391d79bd204980adf/src/grammar/ast.ts#L265) and by [contracts](https://github.com/tact-lang/tact/blob/d86aeab03534d8ccd2407d2391d79bd204980adf/src/grammar/ast.ts#L314). This field should contain identifiers of the corresponding traits, which are `ASTID`, whereas `ASTString` refers to a string literal.

**Comment by anton-trunov** [comment]
definitely!
