### ISSUE TITLE
Unused `ton-compiler` dependency

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#378]
It seems to me that `ton-compiler` is not used and can be safely removed?

**Comment by Gusarich** [comment]
Feel free to open a Pull Request!

**Comment by 0kenx** [comment]
Ok I wasn't sure if it's needed or not

**Comment by anton-trunov** [comment]
Contributions which increase the quality of the codebase are very welcome. In this particular case, I'd also add something like [depcheck](https://www.npmjs.com/package/depcheck) to CI to make sure we won't introduce unused dependencies in the future. Although, depcheck can have false positives which we'd have to handle somehow
