### ISSUE TITLE
Consider introducing a `Slice.loadBool()` extension mutation function

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#411]
It will mirror the `Builder.storeBool()` function and can essentially be an alias to calling `Slice.loadInt(1)`. Having such alias is important for completeness of the stdlib.

Alternatively, we may just make a note in the docs for `Slice.loadInt()` or something.

_Idea taken from: [Comments in Tact Kitchen](https://t.me/tact_kitchen/12)_

**Comment by Gusarich** [comment]
Makes sense
