### ISSUE TITLE
`nativeThrowWhen` usage leads to a FunC compilation error

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#449]
Compilation of the following contract
```
contract Foo {
    get fun foo(): Int {
        nativeThrowWhen(130, true);
        return 42;
    }
}
```

fails with

> error: undefined function `throw_when`, defining a global function of unknown type
      throw_when(130, true);
      ^

**Comment by Gusarich** [comment]
It would also be great to rename it to `nativeThrowIf` but it would break backward compatibility

**Comment by anton-trunov** [comment]
It looks like nobody has used it before, so we can actually do it. And it would be more consistent with FunC

**Comment by novusnota** [comment]
> It looks like nobody has used it before

It wasn't in the docs before and it has no usages on GitHub, so that checks out :)
