### ISSUE TITLE
For the version ^1.1.0, here is some questions:

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact#46]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/36764495/233257521-71657c96-d72d-4413-ad73-cbfcd668d552.png">

1. What is the example for new Logical expressions here? _"&& now does not execute right expression if left is false and || does not execute right expression if left is true."_

For example:
```
......(code)
if (self.status_a == false && (self.level >= msg.target_level || self.item_index == 0) ) {
/// Logic/// 
}
......(code)
```
will not execute anymore? 

2. What is `forward` here means?

_"forward and notify functions that can be used to send messages to other contracts using remaining value of incoming message"_

From my understanding there is no any syntax as `forward` then?

3. `external` support is good!! How we can use it? Any example code here?

**Comment by ex3ndr** [comment]
1. If `status_a` is false it won't try to execute right part of expression `(self.level >= msg.target_level || self.item_index == 0)`. In this case it doesn't matter, but if you have done something that could mutate variables (like reading from slice) it won't be evaluated.

2)
forward is similar to reply, but it allows you to set address. It gets all unused value of incoming message and sends message forward with various parameters

3)
Examples are. coming soon.
