### ISSUE TITLE
Message integer headers specified via octal `0o` or binary `0b` literals get compiled to `#00000000` in TL-B/FunC

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#473]
Consider the following snippet:

```tact
import "@stdlib/deploy";

message(0b101010) Binary {}
message(0o52) Octal {}

contract Example with Deployable {
    receive("just to keep those messages around") {
        let binary = Binary{};
        let octal = Octal{};
    }
}
```

This will produce (apart from other things) those snippets in `tact_Example.storage.fc`:

```func
;;
;; Type: Binary
;; Header: 0x00000000
;; TLB: binary#00000000  = Binary
;;

(tuple) $Binary$_constructor_() inline {
    return empty_tuple();
}

;;
;; Type: Octal
;; Header: 0x00000000
;; TLB: octal#00000000  = Octal
;;

(tuple) $Octal$_constructor_() inline {
    return empty_tuple();
}
```

Meanwhile, specifying the integer header in decimal with or without a leading zero, or in hexadecimal `0x2a` works fine — the resulting header in FunC matches the specified value. Notice, that having any fields in those Messages doesn't affect this issue.

**Comment by anton-trunov** [comment]
This modified contract fails to compile:

```tact
message(0b101010) Binary {}
message(0o52) Octal {}

contract Example {
    receive(msg: Binary) { }
    receive(msg: Octal) { }
}
```

Here is the error message:

```
Tact compilation failed
Error: Invalid allocation: Binary
```

**Comment by novusnota** [comment]
Interesting, so we do recognize that `0b101010` and `0o52` are the same number when it comes to receivers

**Comment by anton-trunov** [comment]
It was a parsing issue
