### ISSUE TITLE
External receivers should be enabled for single contract file compilation

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#484]
If externals are not used there will be no FunC output differences, so to make local debugging and testing easier it would be enable `external` option in the config that we create on-the-fly

**Comment by novusnota** [comment]
You'll only need to add `external: true` in `options` there and it should be done

https://github.com/tact-lang/tact/blob/e2f5eabcd7e6027e36755b858b152f2716f30cb7/src/node.ts#L26
