### ISSUE TITLE
Add missing wrappers for FunC's `store_something()` functions from the `stdlib.fc`

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#496]
1. `store_maybe_ref()` as `Builder.storeMaybeRef()`:

https://github.com/tact-lang/tact/blob/779b0fe736d423d5047222d2443d1ebe7a5dff1e/stdlib/stdlib.fc#L458-L461

_As mentioned in [Tact chat](https://t.me/tactlang/34030)_

2. `store_builder()` as `Builder.storeBuilder()`:

https://github.com/tact-lang/tact/blob/779b0fe736d423d5047222d2443d1ebe7a5dff1e/stdlib/stdlib.fc#L638-L639

**Comment by anton-trunov** [comment]
This is definitely useful for people who wish to go low-level. It would be great to also think of some higher-level constructions which in the end solve the [Y problem](https://en.wikipedia.org/wiki/XY_problem).

**Comment by novusnota** [comment]
Well, we have `.toCell()` and `.fromCell()` now, which are great win in terms of DX and, potentially, gas optimizations in the future.

And if there's a need for manual parsing/construction of cells with very specific bit sizes, my `P.S.` comment by the end of https://github.com/tact-lang/tact/issues/472 may be it.

We'll definitely think about it deeper when the Tact 2.0 starts fledging out :)
