### ISSUE TITLE
Generate inheritance diagram for contracts and traits within a project

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#499]
For instance, the diagram can be produced in the [mermaid](https://mermaid.js.org) format and added to markdown docs on GitHub (for Tact as well). This is useful for auditing purposes as well: to quickly grasp the overall structure of the project.

The diagram should also show the standard traits (all the way down).

**Comment by novusnota** [comment]
Somewhat related, as this diagram may be featured in auto-generated docs: #232

**Comment by anton-trunov** [comment]
great idea!
