### ISSUE TITLE
Port e2e tests to Sandbox

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#510]
[Sandbox](https://github.com/ton-org/sandbox) is the de-facto standard emulator in the TON ecosystem, however Tact's test suite uses [tact-emulator](https://github.com/tact-lang/tact-emulator) for its end-to-end tests. Using the standard instrument would provide further guarantees that the users will observe the same behavior as our tests. Also, we could potentially benefit from the support and contributions by the TON community.

**Comment by Gusarich** [comment]
This one would be easier to complete if generated TS wrappers included some `parseMessage(src: Slice)` which would check source Slice against all known message headers from ABI types and load the one that matches. It can be done by simply generating a bunch of try-catches like this:
```ts
parseMessage(slice: Slice) {
    try {
        return loadDeploy(slice);
    } catch {}
    try {
        return loadDeployOk(slice);
    } catch {}
    // ...
}
```

**Comment by anton-trunov** [comment]
@Gusarich Sounds like a great idea!
