### ISSUE TITLE
Consider making a call to `newAddress(0, 0)` return a null/zero address

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#515]
The following snippet:

```tact
contract Example {
   receive("example") {
       dump(newAddress(0, 0));
   }
}
```

Will cause a compilation error:

```shell
Tact compilation failed
Error: Invalid address hash length: 0
```

That's not a bug per se, however the expected behaviour is to produce a [null/zero address](https://tonscan.org/address/UQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJKZ). In the past, that's how that function worked, see [example on the right in Tact by Example](https://tact-by-example.org/02-addresses).

This was probably overlooked in #237 when resolving #214.

---

Alternative solution would be to introduce a `nullAddress()` function, like I mentioned here: https://github.com/tact-lang/tact/issues/214#issuecomment-2032947204

**Comment by anton-trunov** [comment]
We need an official guarantees from the TON docs that it is really the (a) null address: https://github.com/tact-lang/tact/pull/169#pullrequestreview-1936741339

**Comment by Gusarich** [comment]
There's a difference between "zero address" which is just `0:0000...0000` (completely normal address) and actual `addr_none` which is two zero bits: `addr_none$00 = MsgAddressExt;`.

`newAddress` should return the first option which I think it already does, and for the `addr_none` we should have some separate possibility to get and use it.

**Comment by anton-trunov** [comment]
Let's make sure for 1.4.1 `newAddress(0,0)` returns the same value at compile- and run- time

**Comment by PhiDung-hub** [comment]
> There's a difference between "zero address" which is just `0:0000...0000` (completely normal address) and actual `addr_none` which is two zero bits: `addr_none$00 = MsgAddressExt;`.
> 
> `newAddress` should return the first option which I think it already does, and for the `addr_none` we should have some separate possibility to get and use it.

May I ask is there any consideration for addr_none at the moment. 
For implementing NFT, is using null in place of addr_none a plausible solution?
