### ISSUE TITLE
`initOf` returns different addresses from same arguments

### ISSUE THREAD

**Issue by stanta** [tact-lang/tact#516]
Hi, 
There is two line of code with same arguments, returning DIFFERENT address of contract, based on initOf:

`        dump(contractAddress(initOf BankJettonWallet(owner_address, self.jetton_master)));`
(here: https://github.com/Architec-Ton/banktoken/blob/a781bd5f580bdb2461a9b8769785895e1ffb6e6b/contracts/bank_jetton.tact#L23   )
and  
`        let senderWallet: StateInit = initOf BankJettonWallet (stake.sender, self.BNKjetton);`
(here https://github.com/Architec-Ton/banktoken/blob/a781bd5f580bdb2461a9b8769785895e1ffb6e6b/contracts/bank_staking.tact#L36)

Arguments, sent that function is same, that was with checked lot of iterations (look to picture):
![Screenshot_20240629_185148-1](https://github.com/tact-lang/tact/assets/6910492/2104bdb2-1478-4a90-913c-5e440550c9e8)

Whats wrong?

**Comment by RooTooZ** [comment]
Yes, please, we have same issue in our project.

**Comment by Tiqan** [comment]
We got the same issue... Please fix asap!

**Comment by bogdanovaO** [comment]
we have the same problem too

**Comment by anton-trunov** [comment]
@stanta Are the contract and tests in PR #520 close to what you have? If not, please provide a minimized example contract and tests that demonstrate the issue. Because the tests in that PR actually do not reproduce the issue

**Comment by stanta** [comment]
@anton-trunov 
you can run this test to check issue https://github.com/Architec-Ton/banktoken/blob/a781bd5f580bdb2461a9b8769785895e1ffb6e6b/tests/BNKUnstake.spec.ts

**Comment by anton-trunov** [comment]
@stanta it's too complex and it's not obvious if the issue is not on your side, I just demonstrated we probably don't have it

**Comment by stanta** [comment]
@anton-trunov can you send link to example of code and tests, please?

**Comment by Gusarich** [comment]
> @anton-trunov can you send link to example of code and tests, please?

#520

**Comment by stanta** [comment]
@Gusarich  cab you be mo concrete, please, because of "it's too complex and it's not obvious "

**Comment by anton-trunov** [comment]
@stanta https://github.com/tact-lang/tact/pull/520/files

**Comment by stanta** [comment]
@anton-trunov You tested just parent-child case. I meant in TS calling initOf  with same arguments  from two  TOTALLY different contracts.

**Comment by anton-trunov** [comment]
> I meant in TS calling initOf with same arguments from two TOTALLY different contracts.

I don't understand what you mean: `initOf`s of different contracts would give you different contract addresses, because the address of a contract is defined by _both_ its code and the data used to initialize it. And different contracts will have different code.

**Comment by stanta** [comment]
@anton-trunov taki net ))) look to our  tests results

**Comment by anton-trunov** [comment]
This can be resolved by either not generating ABI IPFS link getters (this will be default in Tact v1.4.1) or by organizing all contracts into one single project.
