### ISSUE TITLE
Unexpected Revert in TON Contract Without Error Message

### ISSUE THREAD

**Issue by ipromise2324** [tact-lang/tact#52]
```
receive(msg: TokenBurn) {
        // Check sender (ensure it's from a valid JettonDefaultWallet)
        let ctx: Context = context();
        let expectedWalletAddress: Address = self.getWalletAddress(msg.owner);
        require(ctx.sender == expectedWalletAddress, "Invalid sender");

        require(self.totalSupply - msg.amount >= 0, "Invalid total supply after burn");
        self.totalSupply = self.totalSupply - msg.amount;
        self.burn(msg.amount, msg.owner, msg.queryId);

    }
```

The reason for the unexpected revert in the TON contract is that the ctx.sender does not match the wallet's address. This inconsistency between the addresses led to the failure of the operation. What's particularly concerning is that during the testing process, the revert did not trigger any error message. 

Is there anyone who can discuss with me what might have happened?

Here is my tact-jetton-code repo:
https://github.com/ipromise2324/Tact-Token-Contract/blob/dd0aeecbf129c9f2e90b03eabed9cfb112f8ac21/contracts/token.tact#L67C148-L67C148

**Comment by howardpen9** [comment]
Saw you just update your smart contract code. 

The code you shared here looks fine for me. 


But I saw potential error is that `self.getWalletAddress(msg.owner)` will get the `Token Wallet Address`, not the caller(aka. Sender) tho.

**Comment by ipromise2324** [comment]
Thanks for helping!
I found out that I have to use toHaveTransaction() to catch error revert.

expect(burnResult.transactions).toHaveTransaction({
            from: player.address,
            to: token.address,
            success: true,
        });
