### ISSUE TITLE
Two small issues with unicodeCodePoint escape sequence in literal strings

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#531]
### Incorrect regex

Regex here (in constant evaluator):
https://github.com/tact-lang/tact/blob/b119b7baac9f8bfa61484757bd226def0d858ab4/src/constEval.ts#L607

Doesn't match the grammar:
https://github.com/tact-lang/tact/blob/b119b7baac9f8bfa61484757bd226def0d858ab4/src/grammar/grammar.ohm#L286

As it allows more than six hexadecimal digits to be specified, while grammar allows from 1 to 6. In that regex on top, the `+` has to be replaced with `{1,6}`.

### Weird bug with specifying from 1 to 6 zeros

The following:

```tact
dump("\u{00000}"); // any number of zeros between 1 and 6 does this
```

...leads to this ugly error message:

```shell
/playground/build/Playground/tact_Playground.code.fc:25:22: error: undefined function `__gen_slice_string_dbbc7025e89eb9b1ec9e8e2c7a2db6869dbb50fba21bf374c86529dc311cede9`, defining a global function of unknown type
      __tact_debug_str(__gen_slice_string_dbbc7025e89eb9b1ec9e8e2c7a2db6869dbb50fba21bf374c86529dc311cede9(), "File contracts/playground.tact:69:9");
                       ^
```

Same goes for `"\u0000"` and `"\x00"` too.

P.S: The maximum valid Unicode code point is U+10FFFF, which makes `dump("\u{110000}")` (and bigger) fail with an RangeError ­— that error can be handled a bit more gracefully :)

**Comment by anton-trunov** [comment]
good catch! can you make a quick PR to resolve this?

**Comment by Gusarich** [comment]
The compilation error occurs due to comments that Tact produces for string constants. I think we have three options:
 * remove these comments completely from generated code
 * escape all special characters (probably via `escape()` js function)
 * forbid null character in strings constants

**Comment by novusnota** [comment]
The last option seems the simplest. Also, we could probably replace null characters with empty spaces. But escaping all special characters may be a more safer option going forward not to introduce unexpected vulnerabilities with crazy unicode code points manipulations

Hmm... Wdyt, @anton-trunov @byakuren-hijiri @jeshecdom @rahulyadav-57

**Comment by anton-trunov** [comment]
Escaping in the generated comments for strings sounds like the best option to me
