### ISSUE TITLE
Replace map operations

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#538]
We should cover the `_replace` and `_replaceget` families of map operations

**Comment by Gusarich** [comment]
@anton-trunov what should `map.replaceGet` return exactly in context of tact maps?

**Comment by anton-trunov** [comment]
@Gusarich As a Tact user, I would expect the following types for the replace functions:
- `replace` should have the type `(map<K, V>, K, V) -> Bool`, where `true` would be returned if the replacement have actually been performed;
- `replaceGet` to have the following type: `(map<K, V>, K, V) -> V?`, i.e. `null` would be returned if no replacement happened and (an old) value of type `V` if a map entry was updated.

**Comment by Gusarich** [comment]
> - `replaceGet` to have the following type: `(map<K, V>, K, V) -> V?`, i.e. `null` would be returned if no replacement happened and (an old) value of type `V` if a map entry was updated.

@anton-trunov what if map is of type `map<K, V?>` already? How will user understand if the value was found and it's just null or it wasn't found?

**Comment by anton-trunov** [comment]
@Gusarich maps do not support optional value types
