### ISSUE TITLE
Conflict in TypeScript code generation for getter function with underscore

### ISSUE THREAD

**Issue by rahulyadav-57** [tact-lang/tact#547]
While generating TypeScript code, if a getter function name contains an underscore, it gets removed and renamed to PascalCase. This results in a naming conflict when there is a function with the same name without the underscore, as both get converted to the same TypeScript function name.

**Example:**

```tact
get fun counter_value(): Int {
    return self.counter;
}
get fun counterValue(): Int {
    return self.counter;
}
```

In the above example, both functions `counter_value` and `counterValue` are generated as `getCounterValue` in TypeScript, leading to a conflict.

**Resulting output:**
```JavaScript
async getCounterValue(provider: ContractProvider) {
    let builder = new TupleBuilder();
    let source = (await provider.get('counter_value', builder.build())).stack;
    let result = source.readBigNumber();
    return result;
}

async getCounterValue(provider: ContractProvider) {
    let builder = new TupleBuilder();
    let source = (await provider.get('counterValue', builder.build())).stack;
    let result = source.readBigNumber();
    return result;
}
```

**Comment by anton-trunov** [comment]
@rahulyadav-57 What solution would be ideal for the online IDE?
