### ISSUE TITLE
Cell overflow caused by contract's specific state layout

### ISSUE THREAD

**Issue by ghost** [tact-lang/tact#569]
In some very specific case the compiler produces code that fails on-chain with exit code 8 "Cell overflow" (in emulator as well).

```
import "@stdlib/deploy";

message SetCost {
    cost: Int? as coins;
}

struct Struct2 {
    c: String;
    d: String;
    e: String;
    f: String;
}

contract SampleTactContract with Deployable {
    owner: Address;
    seqno: Int as uint256 = 0;
    a: Int as uint256 = 0;
    b: Int as uint256 = 0;

    struct2: Struct2;

    author3: Address?;

    cost: Int? as coins;
    address: Address?;
    price: Int? as coins;

    init(owner: Address, struct2: Struct2) {
        self.owner = owner;
        self.struct2 = struct2;
    }

    receive(msg: SetCost) {
        self.cost = msg.cost;
        self.reply("Cost is updated".asComment());
    }
}
```

Repository with a minimal reproducible setup: https://github.com/ak3n/cell-overflow-bug

**Comment by glebthebread** [comment]
+1

**Comment by sounditbox** [comment]
+1

**Comment by anton-trunov** [comment]
Thanks for such a helpful bug report with a repro! Really appreciate it.

We just released a new dev version of Tact: https://www.npmjs.com/package/@tact-lang/compiler/v/1.4.0-dev.20240724 with this issue fixed. And we prepared a wiki page with the recipe how to switch to a dev version of Tact: https://github.com/tact-lang/tact/wiki/Using-unreleased-versions-of-tools-early#dev-versions-of-tact-with-blueprint. Hope it helps. If you could try it out before our official 1.4.1 release I'd be very grateful
