### ISSUE TITLE
`exists` map operation

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#578]
`map.exists(key)` should be equivalent to `map.get(key) != null`

**Comment by Gusarich** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/tact-lang/tact/issues/578?shareId=11d01988-555a-4801-9ab2-e1db231fcc69) saved by @Gusarich using Copilot Workspace v0.22

<details open><summary><b>Topic</b></summary>
<br/>

Does the `map.exists(key)` operation return true if the key exists in the map?

</details>

<details open><summary><b>Before</b></summary>
<br/>

* No, the `map.exists(key)` operation is not implemented in the current code.
* The `map.get(key)` operation is implemented in `src/abi/map.ts`.
* The `map.get(key)` operation returns the value associated with the key or `null` if the key does not exist.
* The `map.exists(key)` operation is not mentioned in any of the existing files.
* To implement `map.exists(key)`, a new function needs to be added to `src/abi/map.ts` that checks if `map.get(key)` is not `null`.



</details>
<details open><summary><b>After</b></summary>
<br/>

- Yes, the `map.exists(key)` operation now returns true if the key exists in the map.
- The `map.exists(key)` operation is implemented in `src/abi/map.ts`.
  - A new function `exists` is added to `MapFunctions` in `src/abi/map.ts`.
  - The `exists` function checks if `map.get(key)` is not `null` and returns a boolean value.
- The `map.exists(key)` operation is equivalent to `map.get(key) != null`.
- The `map.exists(key)` operation is covered with tests in `src/test/e2e-emulated/contracts/maps.tact`.
- we also need to change the `src/test/e2e-emulated/maps.spec.ts`

</details>

<details open><summary><b>Plan</b></summary>
<br/>

* `src/generator/writers/writeStdlib.ts` (CHANGE)
  - Implement `exists` stdlib functions for all map key types
  - we don't actually need to duplicate these functions for different value types. there should only be 3 variatons for key types (int, uint, slice).
* `src/abi/map.ts` (CHANGE)
  - Add a new function `exists` to `MapFunctions`
  - Implement the `exists` function using implemented functions from `src/generator/writers/writeStdlib.ts`
  - we don't need value types here, stdlib functions are named like `__tact_dict_exists_int`
* `src/test/e2e-emulated/contracts/maps.tact` (CHANGE)
  - Add new and modify old functions for `map.exists(key)` operation for all presented key types
  - we don't need messages and receivers for testing `exists` function. we should add getters instead.
  - we don't need getters with `exists` operation calls for intMap 6, 7, 8 and 9 and addrMap 6 and 7.
* `src/test/e2e-emulated/map.spec.ts` (CHANGE)
  - Add test cases for `map.exists(key)` operation
  - Verify that `map.exists(key)` returns true if the key exists in the map
  - Verify that `map.exists(key)` returns false if the key does not exist in the map
  - note what getters are implemented in `src/test/e2e-emulated/contracts/maps.tact` and only use them.
* `src/types/stmts/expr-maps-exists-method.tact` (ADD)
  - Similar to `src/types/stmts/expr-maps-del-method.tact` but for `exists` method.
* `src/types/stmts-failed/expr-map-exists-method-not-bool.tact` (ADD)
  - Similar to `src/types/stmts-failed/expr-map-del-method-is-non-void.tact` but for `exists` method.

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/tact-lang/tact/issues/578?shareId=11d01988-555a-4801-9ab2-e1db231fcc69)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at fc045c8b2bff08d6114232bf634201ddb169ba8f

</details>
