### ISSUE TITLE
Docs about Maps

### ISSUE THREAD

**Issue by Cosmodude** [tact-lang/tact#58]
Currently, if you open the tact docs page (https://docs.tact-lang.org/language/guides/types#maps), there is almost no info about maps. Thus, it's impossible for new devs to start using them.

Please provide more examples and a list of supported methods!

**Comment by howardpen9** [comment]
You are right, I will help with this!

**Comment by howardpen9** [comment]
https://github.com/tact-lang/tact-docs/pull/23
