### ISSUE TITLE
A method to serialize a FunC dictionary

### ISSUE THREAD

**Issue by Cosmodude** [tact-lang/tact#59]
So far I haven't managed to find a method for dictionary creation in Tact.
When using maps(asCell) and structs(toCell) they are transformed into Cells without identifiers and with ordered data. 

Thus, now I can't make the dictionary, that is necessary for NFTs to be compatible with TEP 64 Standard.

**Comment by ProgramCrafter** [comment]
You can either translate FunC's `.store_dict(x)` into `.storeUint(1, 1).storeRef(x.asCell())` or define native function-wrapper for `store_dict`.

**Comment by howardpen9** [comment]
> So far I haven't managed to find a method for dictionary creation in Tact. When using maps(asCell) and structs(toCell) they are transformed into Cells without identifiers and with ordered data.
> 
> Thus, now I can't make the dictionary, that is necessary for NFTs to be compatible with TEP 64 Standard.

You mean the `on-chain` content for metadata right? 
https://github.com/ton-blockchain/TEPs/blob/master/text/0064-token-data-standard.md


Have you solve this? @Cosmodude

**Comment by Cosmodude** [comment]
Yeah, I am talking about on-chain content. 
I found the way to create dict in tact, map does it under the hood. 

Still can't see my collection metadata on any of the explorers

**Comment by Cosmodude** [comment]
You can see examples like "__tact_dict_set_" here:
https://github.com/tact-lang/tact/blob/6bc5eb9d9d74c887f870fe4dc9472fed3f5cd8ad/src/abi/map.ts#L4
