### ISSUE TITLE
Fix Typo in CHANGELOG.md

### ISSUE THREAD

**Issue by QwFRx** [tact-lang/tact#591]
In Roadmap.md there was a line "`let`". The mistake is that the first letter in the sentence should be capitalized. 

---
![IMG_20240722_132843](https://github.com/user-attachments/assets/2f613e37-a769-41d3-9e76-ce8365d091f4)
---

I suggest fixing this problem by writing "`Let`" instead of "`let`".

**Comment by anton-trunov** [comment]
`let` is a keyword and Tact is case-sensitive, so you cannot capitalize it
