### ISSUE TITLE
Type safety and error handling in tact/src/context.ts

### ISSUE THREAD

**Issue by Asidert** [tact-lang/tact#601]
I see several lines in the context.ts where it could be simplified and improved.

My proposal is to refactor lines like:
```
let sh: Record<string, T> = {};
if (this.shared[store]) {
    sh = { ...this.shared[store] };
}
```

To:
```
let sh: Record<string, T> = { ...this.shared[store] } || {};
```

**Comment by anton-trunov** [comment]
thanks for the suggestion, but the Tact team is not looking for any refactor suggestions at this point
