### ISSUE TITLE
Fix formatting for Tact commandments in README.md

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#607]
Headers in the list are not separated from the subsequent explanations.

> This README's section is linked in the main site: https://tact-lang.org/ (Button "Philosophy" at the site's header), but it's just hard to read, because GitHub doesn't preserve newlines and squash title of language property with its description.

**Comment by anton-trunov** [comment]
Would be nice if the numbers in the list had the same text style as the headers, i.e. bold and the same text size.

It looks like this now

<img width="292" alt="image" src="https://github.com/user-attachments/assets/e2f9f7cb-e015-4f39-9d4e-6e3b54396854">

**Comment by s-and-witch** [comment]
> Would be nice if the numbers in the list had the same text style as the headers, i.e. bold and the same text size.

That's true, however GitHub doesn't recognize `### 1. Smth` as an ordered list, it's just a plain title, so 

> 1. ### Title 1
>    Description 1
>   
> 2. ### Title 2
>    Description 2
   
 Is aligned to numbers, while
 
> ### 1. Title 1
>    Description 1
>   
> ### 2. Title 2
>    Description 2 
   
Is not. I decided to follow existing formatting in this case.
