### ISSUE TITLE
`funcId` in `grammar.ohm` of Tact doesn't match the possible range of identifiers and function names in FunC

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#627]
See:
* https://github.com/ton-blockchain/intellij-ton/blob/5b86885dfffdfa23918fe298e53e9d7f11502260/src/main/grammar/FuncLexer.flex#L150
* https://docs.ton.org/develop/func/literals_identifiers#identifiers

**Comment by anton-trunov** [comment]
btw, the two descriptions do not really correspond. It seems to me the grammar in the TON IntelliJ plugin admits `42` as a valid FunC identifier

**Comment by novusnota** [comment]
> btw, the two descriptions do not really correspond. It seems to me the grammar in the TON IntelliJ plugin admits 42 as a valid FunC identifier

Yup, I discovered divergencies in tests too. I'll stick to the TON docs and the source code of FunC
