### ISSUE TITLE
Typechecker should not allow mutation of a constant via mutating function

### ISSUE THREAD

**Issue by jeshecdom** [tact-lang/tact#658]
In the following code, the typechecker should complain:
```
extends mutates fun F (self: Int): Int {
    let i = 12;
    self += i;
    return i;
}

const C1: Int = 1;   
const C2: Int = C1.F();      // 12
const C3: Int = C1;           // 13
```
Here, the call `C1.F()` will change the value of constant `C1` to `13` via the mutating function `F`.

**Comment by anton-trunov** [comment]
Wait, what branch are you on? Because I'm getting the following error when using the current main branch (commit bff157e0812c65e84e9d1fc851b3adcc70b328e9)

```tact
💼 Compiling project test ...
Tact compilation failed
Error: test.tact:8:17: Cannot evaluate expression to a constant: calls of "F" are not supported at this moment
Line 8, col 17:
  7 | const C1: Int = 1;   
> 8 | const C2: Int = C1.F();      // 12
                      ^~~~~~
  9 | const C3: Int = C1;          // 13
```

**Comment by anton-trunov** [comment]
Ah, I see, that's a const-eval error, so you are saying it should be caught during typechecking

**Comment by anton-trunov** [comment]
Actually, we allow mutating temporary objects like `C1.F()`, because it's essentially `F(C1)`. See, for instance, [`src/test/e2e-emulated/contracts/mutating-method-chaining.tact`](https://github.com/tact-lang/tact/blob/main/src/test/e2e-emulated/contracts/mutating-method-chaining.tact). So, if `C3` gets the value `13` as in your example above, this looks like a const-eval bug to me.

**Comment by jeshecdom** [comment]
But `C1` is declared as a constant. It would have two different values during the execution of the program, `1` and `13`. I think this should be caught before reaching const-eval because const-eval is an optimization phase: if we remove const-eval, the semantics of the program should remain intact. Or maybe I am misunderstanding the purpose of const-eval.

**Comment by jeshecdom** [comment]
Ok. Since Tact does constant substitution, `C1.F()` will actually be `1.F()`. So, no modification of `C1` actually takes place. Hence, this should be taken into account by const-eval.
