### ISSUE TITLE
Trait "Deployable" is not working properly

### ISSUE THREAD

**Issue by justafewtests** [tact-lang/tact#667]
Here is code of simple contract factory - it should deploy instances of itself when recieves "DeployContract" type of message:

```
import "@stdlib/deploy";

message DeployContract{
    id: Int as uint64;
}

contract ContractFactory with Deployable {
    id: Int as uint64;

    init(id: Int) {
        self.id = id;
    }

    get fun myAddress(): Address{
        return myAddress();
    }

    get fun otherAddress(otherId: Int): Address{
        let init: StateInit = initOf ContractFactory(otherId);
        return contractAddress(init);
    }

    receive(msg: DeployContract) {
        let init: StateInit = initOf ContractFactory(msg.id);
        let address: Address = contractAddress(init);

        send(SendParameters{
            to: address,
            value: 0,
            mode: SendRemainingValue + SendIgnoreErrors,
            bounce: true,
            code: init.code,
            data: init.data,
            body: Deploy{queryId: 0}.toCell()
        });
    }

    get fun id(): Int{
        return self.id;
    }
}
```

Test are working perfectly, but if I deploy it and try to send "DeployContract" message to ContractFactoy the following will happened:
1) Send "DeployContract" message from wallet to ContractFactory (ok) <br>
2) Send "Deploy" message from ContractFactory to instance (error: exit code 130) <br>

Here is the example in tonviewer: https://testnet.tonviewer.com/transaction/13f8ab5feef7a5c103ac8dfa2bf1c9bdc12a9ac95d55d2caf288d65106caa734

**Comment by Gusarich** [comment]
> 2\. Send "Deploy" message from ContractFactory to instance (error: exit code 130)

No. The `130` error occurs on processing `DeployOk` notification message and it doesn't affect the result at all in this case.

You can just add an empty (or not empty) handler of `DeployOk` message to your factory and it will complete without errors.
