### ISSUE TITLE
Document how to use the master-branch Tact version with external tools like Blueprint

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#67]
This is useful for debugging purposes

**Comment by Gusarich** [comment]
do you mean installing Tact locally from repo and linking it to the project?

**Comment by anton-trunov** [comment]
@Gusarich that's correct

**Comment by Gusarich** [comment]
Shouldn't this issue be in https://github.com/tact-lang/tact-docs repo?

**Comment by novusnota** [comment]
Actually, this is already in the wiki: https://github.com/tact-lang/tact/wiki/Using-unreleased-versions-of-tools-early#dev-versions-of-tact-with-blueprint. So this should be closed :)
