### ISSUE TITLE
Issues Retrieving Collection and Individual Content from TonAPI and Toncenter

### ISSUE THREAD

**Issue by nxved** [tact-lang/tact#672]
Collection and individual content are returning null when querying TonAPI and Toncenter HTTP endpoints. However, I am able to correctly retrieve the NFT URI using the get_nft_data function. Additionally, NFTs are displayed without issues on GetGems. Tonkeeper fails to display NFT images due to its reliance on TonAPI.

**Gist Link of contracts, scripts, package.json**
**https://gist.github.com/nxved/217b473ba275ddfe582b4ad0a225ea01**

tonapi response
![image](https://github.com/user-attachments/assets/d5193ea1-0fdc-4a5c-a281-2a4d4e59dfb7)

ton keeper:
![image](https://github.com/user-attachments/assets/b3d9b438-f1b6-4fc5-9096-edb37920bade)

**Comment by anton-trunov** [comment]
Looks like this has been resolved in a discussion elsewhere
