### ISSUE TITLE
Importing traits from `node_modules`

### ISSUE THREAD

**Issue by alan890104** [tact-lang/tact#68]
I'm looking to publish my `tact` traits on npm and then reuse them in other repos by importing from `node_modules`

**Comment by alan890104** [comment]
A possible solution may be simply resolve them before compiling, as we discuss in Ton Dev Community

https://t.me/tondev_eng/36459:

> If it is URI, it helps a lot to develop the library from community and update the clients
but it can be a local path from modules folder by configuring compiler file for imports 

```
"imports" : [
    "@traits" : "path/to/node_modules/traits/package"
]
```

**Comment by alan890104** [comment]
Similar to #77

**Comment by anton-trunov** [comment]
Closing this for now. We might return to this issue in the future. See #147
