### ISSUE TITLE
`as remaining` for map value types silently does nothing

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#687]
Specifying `remaining` for the `Cell` as the map value type does nothing — the cell would still be stored as a reference:

```tact
struct Nope {
    // dict<uint8, ^cell> in TL-B notation, despite the `remaining` specified
    m: map<Int, Cell as remaining>;
}
```

**Comment by Gusarich** [comment]
What would be the correct behavior?

**Comment by anton-trunov** [comment]
It seems to me for maps it does not really make sense to allow `as remaining` neither for key types, nor for value types. Because the meaning of `as remaining` is "the rest of the data (in the cell we are parsing now)", so it can only be allowed for struct-like data and only as an annotation for the last element.

**Comment by novusnota** [comment]
Isn't it banned already? Here:

https://github.com/tact-lang/tact/blob/12def54b4b17417dda06cbf0e7e411f003504f8a/src/types/resolveDescriptors.ts#L79-L87

Maps with any `as` annotations for Cell values (and, incidentally, keys) are prohibited, thus prohibiting `as remaining` too.

**Comment by anton-trunov** [comment]
Yes, you are right, this was fixed
