### ISSUE TITLE
Allow nullable types in "extends mutates" functions

### ISSUE THREAD

**Issue by ProgramCrafter** [tact-lang/tact#70]
TVM dictionaries are nullable cells. To work with them, methods need to accept `Cell?`, and it's currently impossible to mark such function "extends mutates", leading to constructions like `dict = udict_store_ref(dict, 256, "name".sha256(), ...);`.

**Comment by Gusarich** [comment]
@ProgramCrafter why are you using manually defined `udict_store_ref` function instead of `.set` map method?

**Comment by ProgramCrafter** [comment]
@Gusarich at that point I totally wasn't aware of `.set` method.

Though, I'd still like option to have methods on `Cell?` to work on dynamically-sized-keys map.

**Comment by Gusarich** [comment]
> Though, I'd still like option to have methods on `Cell?` to work on dynamically-sized-keys map.

In which case do you have a variable of type `Cell` instead of `Map` that should still be treated as a `Map`?
