### ISSUE TITLE
Unclear abstract functions behavior, not covered by docs

### ISSUE THREAD

**Issue by imartemy1524** [tact-lang/tact#723]
## The problem
I'm trying to develop smart contract in tact, but got some problems with understanding concept of abstract function.
Imagine situation, where there are 2 traits: `Animal` and `Dog`, and trait `Dog` inherits `Animal`, while `Animal` has abstract function. Where should it be implemented? Inside trait `Dog`, or inside smart contract? Because neither way works.

## Example
For example, I want to do smthng like this:
```rust
//base traut
trait Animal{
    abstract fun getType(): String;
    abstract fun getSound(): String;
    fun message(): String{
        return beginString().concat("I am a ").concat(self.getType()).concat(" and I make ").concat(self.getSound()).toString();
    }
    receive("make sound"){
        self.reply(self.message());
    }
}
//I want to make trait, which inherits previous trait and overrides abstract methods... But I can't??? Why?
trait Dog with Animal{
    override fun getType(): String{
        return "Dog";
    }
    override fun getSound(): String{
        return "Woof";
    }
}

//Contract, which implements Dog trait and other traits
contract DogContract with Dog, Ownable{

    //some other messages
    receive("throw away"){
        self.owner = null;
    }
    receive("adopt"){
        require(self.owner == null, "Already adopted");
        self.owner = sender();
    }
}
```

But when one tries to compile code above, next error occurs:
```
Overrides functions must be defined within a contract
```
However, if one tries to implement this abstract functions directly in contract code, then he gets next error message:
```
Error: contracts/master.tact:14:1: Trait "Animal" requires function "getType"
Line 14, col 1:
> 14 | trait Dog with Animal{
       ^~~~~~~~~~~~~~~~~~~~~~
```
Is there a solution for this? 
Because official documentation doesn't covert this behavior (when one contract inherits another with abstract function).

P.S. the only thing about traits I found in docs was [this](https://docs.tact-lang.org/book/types#traits)

**Comment by anton-trunov** [comment]
@imartemy1524 Thanks for yet another awesome report! Overriding abstract functions in traits should be allowed. The fix is ready: check out if the test https://github.com/tact-lang/tact/pull/724/files#diff-131b74e70558c6d137ecfe43a0d649ea55649b173be784043265037e221ca3db matches your intuition
