### ISSUE TITLE
Relative imports don't work in upward direction

### ISSUE THREAD

**Issue by defi-pickle** [tact-lang/tact#73]
I am encountering issues with relative imports, which don't seem to function intuitively, especially when I try to import files from a different directory. When I import files from the same directory using the syntax `import "./other_file.tact";`, everything operates smoothly. However, problems emerge when I attempt to import files from a parent or sibling directory with the syntax `import "../other_file.tact";`.

I have an extensive folder structure with many contracts, and my goal is to share some utility files among them while adhering to a standard folder structure. My folder structure is organized as follows:

```
contracts
|--utils
   |--some_file.tact
|--dex
   |--dex_file.tact
```
I aim to maintain this structure while facilitating the sharing of utility files across different contracts. However, the relative import issues are preventing me from achieving this. Question is: **Can we achieve such imports in tact?**

**Comment by defi-pickle** [comment]
link to the same issue on blueprint https://github.com/ton-org/blueprint/issues/59

**Comment by logvik** [comment]
Please, specify your OS

**Comment by defi-pickle** [comment]
```
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.87 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
```

Also i am using `@tact-lang/compiler@1.1.3` and `@ton-community/blueprint@0.12.0`

**Comment by defi-pickle** [comment]
If you need a hand in adding this feature just let me know where should i start.
