### ISSUE TITLE
Sending empty message throws at FunC compilation

### ISSUE THREAD

**Issue by Tarnadas** [tact-lang/tact#74]
Hey,

if I try to send an empty message the FunC compiler throws a cryptic error message:

```
Func compilation error:...:184:14: error: previous function return type tuple cannot be unified with return statement expression type (): cannot unify type () with tuple
```

Example:
```
message MyMessage {
}

contract MyContract {
    receive("send") {
        send(SendParameters {
            to: context().sender, 
            value: 0, 
            bounce: false,
            mode: SendIgnoreErrors,
            body: MyMessage {}.toCell()
        });
    }
}
```

After investigating the Tact compiler output it was clear that the error was caused by the empty message.

**Comment by imsk17** [comment]
Hi, I am also facing a similar error and i have checked that there are no empty messages.

**Comment by anton-trunov** [comment]
@imsk17 Could you please provide your Tact source code and the exact error message you see?
