### ISSUE TITLE
Suggestion: Impose stricter limitations on message and struct names

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#80]
Currently, according to the [grammar.ohm](https://github.com/tact-lang/tact/blob/main/src/grammar/grammar.ohm), type literals must start with an uppercase letter, while structs and messages do not yet have such limitation.

<p></p>
<img style="display:inline;" width="48%" src="https://github.com/tact-lang/tact/assets/68142933/c4f41372-c7d4-43f6-b36f-d46fbeb0cf15" />
<img style="display:inline;" width="48%" src="https://github.com/tact-lang/tact/assets/68142933/24175149-46f8-4e50-97e9-b7558b703990" />
<p></p>

This results in a situation, where, according to the Ohm grammar, messages and structs can start with an lowercase (!) letter, but no such name can be used as a type, making such messages and structs useless.

Therefore, I propose imposing stricter limitations on message and struct names, such that they must be named according to the rules of `typeLiteral`' and not `id`. See the current grammar on the left and the change (`id` -> `typeLiteral`) applied on the right:

<p></p>
<img style="display:inline;" width="42%" src="https://github.com/tact-lang/tact/assets/68142933/15509fa9-1829-4467-96ce-8e9bdb67d2f3" />
<img style="display:inline;" width="52%" src="https://github.com/tact-lang/tact/assets/68142933/951a047d-0ed1-4ad0-b718-cd4709f04cc6" />
<p></p>

**Comment by anton-trunov** [comment]
Yep, good catch! Does PR #81 solve it for you?

**Comment by novusnota** [comment]
@anton-trunov Yes, it does! Thanks for the rapid response ⚡

**Comment by anton-trunov** [comment]
Awesome! Merged

**Comment by novusnota** [comment]
@anton-trunov Hey, sorry to necropost, but I've overlooked the [line 43 in grammar.ohm](https://github.com/tact-lang/tact/pull/81/commits/1e1af11a4ff3abc2797d54cf81e4b7b31c6578bf#diff-6b08d1f97b164bb88197a2f0d176493339782889861667d5fef0503c3f78ff71R43) and missed that you didn't change `id` to `typeLiteral` there. My bad :(

Could you please send a follow-up PR for it as well?
