### ISSUE TITLE
Throwing functions from imported FunC sources don't throw when called from the Tact bindings to them

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#822]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
/*
    Inside that file there's a simple function:
    () throw_test() {
        throw(1337);
    }
*/
import "./throw-shenanigans.fc";

@name(throw_test)
native throwTest();

contract Showcase {
    /// For deployment
    receive() {}

    /// For showcase
    receive("I won't throw") {
        throwTest(); // ← doesn't throw!
        dump("You'll see this message");
    }
}
```

### What happened?

Exit code $0$ and successful transaction overall.

### What did you expect?

I expected an exit code $1337$ in my tests.

### How do you run Tact?

Blueprint

### Anything else?

That might be some issue in Sandbox and not Tact, although there's one particular case that may indicate that the bug is on the Tact side — the function [`dnsInternalNormalize()`](https://docs.tact-lang.org/ref/stdlib-dns#dnsinternalnormalize) from [`@stdlib/dns`](https://docs.tact-lang.org/ref/stdlib-dns) is a binding to the respective FunC function `dns_internal_normalize()` implemented in [`dns.fc`](https://github.com/tact-lang/tact/blob/main/stdlib/libs/dns.fc) file. The problem is that this FunC function is supposed to throw whenever a slice with any references is passed to it:

```func
slice dns_internal_normalize(slice src) inline_ref {
    throw_unless(src.slice_refs() == 0, 134); ;; Invalid argument error
    ;; ... etc. etc. etc.
}
```

But when bound to a Tact function `dnsInternalNormalize()`, it no longer throws when receiving such slice!

**Comment by anton-trunov** [comment]
You need to make your `throw_test` FunC function `impure` then it will work. We need to fix `dns.fc` file

**Comment by novusnota** [comment]
Sure, I'll fix it in a moment or two — I'm thinking on adding `dnsInternalNormalize()` to the exit code tests, PR of which I'm updating right now.

**Comment by anton-trunov** [comment]
@novusnota There is `dns.spec.ts` in the e2e tests, we should add a test there

**Comment by anton-trunov** [comment]
In general, exit codes are part of a contract's interface and the corresponding tests should check the exit codes as well (we should actually enhance our testing page in the tact docs should how it should be done)

**Comment by novusnota** [comment]
Omg, I found the issue (it took forever) — the order of arguments in `throw_unless` was reversed. That is, the `dns.fc` contained an invalid call to `throw_unless` all this time!
