### ISSUE TITLE
Suggestion: create a CSpell dictionary of all TVM instructions

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#826]
And utilize it via `dictionaryDefinitions` and `dictionaries` properties in `cspell.json`, such that there would be no need in manually adding the individual instructions to the allowed `words`. Nothing fancy, the CSpell dictionary is just a plain txt file with words placed on each line.

Can try to generate it from [instructions.csv](https://github.com/ton-community/ton-docs/blob/main/docs/learn/tvm-instructions/instructions.csv) or [hacker-volodya/tvm-spec](https://github.com/hacker-volodya/tvm-spec).

Additional info:
* https://cspell.org/docs/dictionaries/
* https://github.com/streetsidesoftware/cspell-dicts

P.S.: As a bonus, the LSP can suggest words from it. And this might be a good start for the future typechecking and gas usage analysis of those instructions :)

**Comment by anton-trunov** [comment]
Great suggestion, let's do it for the 1.6 release
