### ISSUE TITLE
ability to import tact files from npm 

### ISSUE THREAD

**Issue by hitaspdotnet** [tact-lang/tact#84]
```solidity
import "@npm/@hitasp/npm_imported";
import "@npm/dynasty/another_imported";
```
Can help for #77 integration. 

I can send PR for this if approved.

**Comment by anton-trunov** [comment]
What is the difference between this issue and #77?

**Comment by hitaspdotnet** [comment]
@anton-trunov that is about configurable paths and http code resolver, but this only support node_modules. I just saw #68, and this could be labeled as duplicate.
PR is ready to send.

**Comment by anton-trunov** [comment]
> PR is ready to send

Sure, will happily review it

**Comment by anton-trunov** [comment]
There is no consensus on this feature so far, please see this discussion: #147. Closing this for now, but we might come back to the issue of imports from some centralized resources later. Right now your best workaround is to vendor your dependencies.
