### ISSUE TITLE
Re-write `exit-codes.mdx` into an article of the Book

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact#887]
Great [tact-fireworks](https://github.com/ton-community/tact-fireworks) may suit as a starting point. Furthermore, the [Fireworks contract](https://github.com/ton-community/tact-fireworks/blob/3e7c4ec23d6d663a2f8a73d1d12eef9fe0780580/contracts/fireworks.tact#L38) should be split into many smaller contracts (or `receive()` functions) to showcase one error and exit code per one transaction, as suggested by @anton-trunov.

Additional things to fix:
* Table of Contents for every exit code through headers
* Disallow LaTeX numbers in headers for better search
* Grammar, spelling, punctuation
* Add missing exit codes, i.e. exit code 11 is not documented, and there are others!

Additional links:
* [Writing Tests Examples](https://docs.ton.org/develop/smart-contracts/testing/writing-test-examples)
* [Fireworks in FunC](https://github.com/ton-community/fireworks-func)
* [Description of exit codes thrown in Fireworks](https://docs.ton.org/develop/smart-contracts/testing/writing-test-examples)
* [Exit Codes page in Tact docs](https://docs.tact-lang.org/book/exit-codes)
* [Extra exit codes of Tact](https://github.com/tact-lang/tact/blob/main/src/abi/errors.ts)
* [Exit codes of TVM](https://docs.ton.org/learn/tvm-instructions/tvm-exit-codes)

Also — describe what "cannot be faked" means for exit code -14, see: https://github.com/ton-blockchain/ton/blob/20758d6bdd0c1327091287e8a620f660d1a9f4da/crypto/vm/vm.cpp#L492.

Also, describe what they are in general and how they occur.

**Comment by anton-trunov** [comment]
Tact generates exit codes for `require` depending on the concrete error message string and thus the exit codes can be arbitrary
