### ISSUE TITLE
Hackathon feedback - why can't receivers be simple functions?

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#9]
Users found this code confusing:

```
message Add {
    amount: Int as uint32;
}

message Subtract {
    amount: Int as uint32;
}

contract Counter {

    receive(msg: Add) {
        // ...
    }

    receive(msg: Subtract) {
        // ...
    }
}
```

Questions:
* "why don't these functions have names?"
* "how can you know which function you're calling?"

They proposed a more familiar syntax that would not bring questions and will look more like other languages:

```
contract Counter {

    recv fun Add(amount: Int as uint32) {
        // ...
    }

    recv fun Subtract(amount: Int as uint32) {
        // ...
    }
}
```

**Comment by ex3ndr** [comment]
This is due the fact that calling this method more than once could lead to a huge number of possible bugs. This functions are not callable by anything except blockchain itself.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tal Kol ***@***.***>
Sent: Sunday, February 26, 2023 3:48:21 PM
To: tact-lang/tact ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tact-lang/tact] Hackathon feedback - why can't receivers be simple functions? (Issue #9)


Users found this code confusing:

message Add {
    amount: Int as uint32;
}

message Subtract {
    amount: Int as uint32;
}

contract Counter {

    receive(msg: Add) {
        // ...
    }

    receive(msg: Subtract) {
        // ...
    }
}


Questions:

  *   "why don't these functions have names?"
  *   "how can you know which function you're calling?"

They proposed a more familiar syntax that would not bring questions and will look more like other languages:

contract Counter {

    recv fun Add(amount: Int as uint32) {
        // ...
    }

    recv fun Subtract(amount: Int as uint32) {
        // ...
    }
}

**Comment by talkol** [comment]
This could still be the case.

Notice that the proposed syntax starts these function with `recv fun Add()` so they're easily identifiable - meaning the compiler will not allow you to call `recv` functions directly. The proposal is just syntactic sugar, they're not actually internal functions.

**Comment by Gusarich** [comment]
having message structs defined separately is better.
for example, in jetton wallets you both send and receive `InternalTransfer` messages.

**Comment by novusnota** [comment]
If anything, I'd simply like a small alias `internal`, which would be the same as writing `receive`.

Rationale goes as follows — one can receive messages in Tact, which can be of 2 main types: internal and external, plus one sub-type for bounced messages. Therefore, we could have: `internal` (aka `receive`), `bounced`, `external`.

UPD: or `recv_internal`, `recv_bounced` and `recv_external` to be FunC-like :)

**Comment by anton-trunov** [comment]
I think keeping contract interfaces explicitly in messages is way better than recovering this information from function signatures.
