### ISSUE TITLE
Improve exhaustiveness checks

### ISSUE THREAD

**Issue by jubnzv** [tact-lang/tact#915]
We could improve compile-time checks provided by the TypeScript compiler introducing [the `unreachable` function](https://github.com/nowarp/misti/blob/466e2663d76eecd7db38efe90f0d45065077f867/src/internals/util.ts#L18):
```typescript
export function unreachable(value: never): never {
  throw InternalException.make(`Reached impossible case`, { node: value });
}
```

It accepts the parameter `never`, so it could be used to perform a static exhaustiveness checks for `switch` clauses:
```
switch (node.kind) {
  case "id":
    // ...
  // other cases
  default:
    unreachable(node);
}
```

If some of the node kinds are not covered by the `case` clauses, we'll get a compilation error:
![picture](https://github.com/user-attachments/assets/5a35529f-9967-4400-9031-f0048f4abc22)

That's quite useful especially to avoid regressions when changing enum types implementations.

**Comment by verytactical** [comment]
That's what TypeScript devs [do in its compiler](https://github.com/microsoft/TypeScript/blob/main/src/compiler/debug.ts#L273), so it seems to be as close to a recommended approach as it gets.

I looked up how they [intend to use it](https://github.com/search?q=repo%3Amicrosoft%2FTypeScript+Debug.assertNever&type=code), and results were quite inconclusive: they use it standalone, with `return` and even with `throw` in front.

_EDIT._ There's a lot of other shiny functions in that file too...
