### ISSUE TITLE
Getters doesn't work correctly for nullable strings

### ISSUE THREAD

**Issue by imartemy1524** [tact-lang/tact#918]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
struct UserData{
    nickname: String?;
    avatar: String?;
}

contract User with Deployable {
    // a lot of random properties
    nickname: String? = null;
    avatar: String? = "bob.avatar";

    init(){}
    get fun data(): UserData{
        return UserData {
            nickname: self.nickname,
            avatar: "some random string, which for some reasons always null"
        };
    }
}
```

### What happened?

Tact didn't compiled `typescript` the code correctly: instead of constant "string" variable null returned for some reason, when calling getter.

BUT! If one change default value of **class field** "nickname" to nonnull default value, the getter would return correct value. 

### What did you expect?

I expected that generated code work correctly
 

### Steps to reproduce

```
git clone https://github.com/imartemy1524/tact-getter-bug
cd tact-getter-bug
npm i
npx blueprint build --all
npm test
```

### How do you run Tact?

Blueprint

### Anything else?

GIT repository with tact code, which contains bug: [click](https://github.com/imartemy1524/tact-getter-bug)

I debugged the code a bit, and it seems, that `tupleReader.readStringOpt` from `@ton/core` works incorrectly: 
```typescript
        let popped = this.peek();
        if (popped.type === 'null') {
            return null;
        }
        let s = this.readCell().beginParse();
        return s.loadStringTail();
```

If `propped.type === 'null'`, it doesn't skip current element, which leads to -1 shift for next elements

**Comment by anton-trunov** [comment]
Thanks for the report and for the investigation of the root cause. I opened a PR with a provisional fix: https://github.com/ton-org/ton-core/pull/47. I tested it locally on your example and it seems to work. It would be nice if you found some time to review that fix.
