### ISSUE TITLE
`.husky/pre-push` should lint tact-docs

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#923]
This would help avoid CI failures dues to typos in the Tact docs

**Comment by novusnota** [comment]
Good suggestion!

But the thing is, I've made `cspell.json` in the root expliticly ignore the inner contents of docs, which are checked by the inner CSpell and it's own `docs/cspell.json`. In short, that means that if there were no changes in the `/docs` folder, no typos should be reported. So this suggestion really covers the cases when there were changes AND the dev forgot to run `yarn spell` inside `/docs`

**Comment by anton-trunov** [comment]
I want to be that dev who is allowed to forget running things in a sub-directory :)
