### ISSUE TITLE
`late` modifier

### ISSUE THREAD

**Issue by mhbdev** [tact-lang/tact#93]
# Situation
Think of non-null variable that would be set later with different values on different conditions.

# Proposal
I think it would be nice if we can define a variable with `late` modifier.
something like `late let test: Int;` so we can set its value later.

```tact
late let test: Int;

if(condition0) {
    test = 0;
} else {
    test = 1;
}

dump(test.toString());
```

**Comment by anton-trunov** [comment]
This case can be now resolved using a conditional expression which was implemented in #94. Closing this one now. Feel free to reopen if there is a compelling use case
