### ISSUE TITLE
bounced function not getted field from message

### ISSUE THREAD

**Issue by Tinh96nb** [tact-lang/tact#940]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
message(0x0f8a7ea5) JettonTransfer {
    destination: Address;
    query_id: Int as uint64;
    amount: Int as coins;
    response_destination: Address;
    custom_payload: Cell?;
    forward_ton_amount: Int as coins;
    forward_payload: Slice as remaining;
}
...

bounced(msg: bounced<JettonTransfer>){
   dump(msg.destination); // error, can not compiled
}
```

### Relevant Tact/build system log output

```shell
Type bounced<"JettonTransfer"> does not have a field named "destination"
```

### What happened?

Can not get field from bounce message!
![photo_2024-10-10 15 59 10](https://github.com/user-attachments/assets/cd7faddf-f1d2-46de-9c7e-c3dcf78299d5)

### What did you expect?

Can get all field from bounce message!

### How do you run Tact?

Blueprint

**Comment by anton-trunov** [comment]
https://docs.tact-lang.org/book/bounced/#caveats

> Currently, bounced messages in TON have only 224 usable data bits in the message body and don’t have any references.

And addresses usually need 267 bits, so you cannot recover it from a bounced message
