### ISSUE TITLE
self destruct in Tact

### ISSUE THREAD

**Issue by ParsaAminpour** [tact-lang/tact#973]
quick question:

Is there a function in Tact similar to selfdestruct in Solidity? 
If there's a way to remove a contract, where do the stored funds go? 
And if not, how would you go about removing a contract? 
I'm asking mainly regarding handling something like a `TON mishandling` in a contract

thanks

**Comment by anton-trunov** [comment]
https://docs.tact-lang.org/book/message-mode/

you are probably looking for `SendDestroyIfZero`
