### ISSUE TITLE
`SendParameters`: Constant for `mode: 0`

### ISSUE THREAD

**Issue by Esorat** [tact-lang/tact#988]
We can define a constant for the `0` mode value to improve readability and describe the default behavior more clearly. This constant will replace any direct usage of `0` in the `mode` field throughout the codebase, as commonly seen in real-world contracts.
This change will make choosing the default mode more explicit and could be leveraged by `SuspiciousMessageMode`, which detects such cases: https://github.com/nowarp/misti/pull/199.

Context: https://docs.tact-lang.org/book/message-mode/

**Comment by anton-trunov** [comment]
The `mode` field has `0` as the default value, so people often don't even mention it, like `code` and `data` if they don't want to deploy a contract.

```
struct SendParameters {
    bounce: Bool = true;
    to: Address;
    value: Int;
    mode: Int = 0;
    body: Cell? = null;
    code: Cell? = null;
    data: Cell? = null;
}
```

**Comment by jubnzv** [comment]
@anton-trunov We have seen many cases in real-world contracts where people simply write `mode: 0`. It seems they are either trying to explicitly specify the mode or are unsure about the default value.

Should we just ignore these cases or raise warnings asking them to remove the `mode` parameter?

**Comment by anton-trunov** [comment]
We can add `const SendDefaultMode: Int = 0;` (or `SendDefaultMode`) to `send.tact` for the sake of completeness
